#!/bin/bash
##
## This source file is part of the valkey-swift project
## Copyright (c) 2025 the valkey-swift project authors
##
## See LICENSE.txt for license information
## SPDX-License-Identifier: Apache-2.0
##

set -eu

here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function genWithoutContextParameter() {
    how_many=$1

    echo ""

    echo "    @inlinable"
    echo -n "    public func transaction<C0: ValkeyCommand"
    for ((n = 1; n<how_many; n +=1)); do
        echo -n ", C$((n)): ValkeyCommand"
    done

    echo -n ">(_ c0: C0"
    for ((n = 1; n<how_many; n +=1)); do
        echo -n ", _ c$((n)): C$((n))"
    done
    echo -n ") async throws -> (Result<C0.Response, Error>"
    for ((n = 1; n<how_many; n +=1)); do
        echo -n ", Result<C$((n)).Response, Error>"
    done
    echo ") {"
    echo -n "        guard let responses = try await self.execute(MULTI(), "
    for ((n = 0; n<how_many; n +=1)); do
        echo -n "ValkeyRawResponseCommand(c$((n))), "
    done
    echo "EXEC()).$((how_many+1)).get() else { throw ValkeyClientError(.transactionAborted) }"
    echo "        return responses.decodeElementResults()"
    echo "    }"
}

{
cat <<"EOF"
//
// This source file is part of the valkey-swift project
// Copyright (c) 2025 the valkey-swift project authors
//
// See LICENSE.txt for license information
// SPDX-License-Identifier: Apache-2.0
//
// NOTE: THIS FILE IS AUTO-GENERATED BY dev/generate-transaction-commands.sh
EOF
echo

echo "import NIOCore"
echo ""
echo "@available(valkeySwift 1.0, *)"
echo "extension ValkeyConnection {"
# note:
# - widening the interval below (eg. going from {1..15} to {1..25}) is Semver minor
# - narrowing the interval below is SemVer _MAJOR_!
for n in {1..10}; do
    genWithoutContextParameter "$n"
done
echo "}"
} > "$here/../Sources/Valkey/Connection/ValkeyConnection+transactions.swift"

swift format format -i "$here/../Sources/Valkey/Connection/ValkeyConnection+transactions.swift"