//===----------------------------------------------------------------------===//
//
// This source file is part of the valkey-swift open source project
//
// Copyright (c) 2025 the valkey-swift project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of valkey-swift project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// This file is autogenerated by ValkeyCommandsBuilder

import NIOCore

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

/// Adds elements to a HyperLogLog key. Creates the key if it doesn't exist.
@_documentation(visibility: internal)
public struct PFADD: ValkeyCommand {
    public typealias Response = Int

    @inlinable public static var name: String { "PFADD" }

    public var key: ValkeyKey
    public var elements: [String]

    @inlinable public init(_ key: ValkeyKey, elements: [String] = []) {
        self.key = key
        self.elements = elements
    }

    public var keysAffected: CollectionOfOne<ValkeyKey> { .init(key) }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("PFADD", key, elements)
    }
}

/// Returns the approximated cardinality of the set(s) observed by the HyperLogLog key(s).
@_documentation(visibility: internal)
public struct PFCOUNT: ValkeyCommand {
    public typealias Response = Int

    @inlinable public static var name: String { "PFCOUNT" }

    public var keys: [ValkeyKey]

    @inlinable public init(keys: [ValkeyKey]) {
        self.keys = keys
    }

    public var keysAffected: [ValkeyKey] { keys }

    public var isReadOnly: Bool { true }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("PFCOUNT", keys)
    }
}

/// Merges one or more HyperLogLog values into a single key.
@_documentation(visibility: internal)
public struct PFMERGE: ValkeyCommand {
    @inlinable public static var name: String { "PFMERGE" }

    public var destkey: ValkeyKey
    public var sourcekeys: [ValkeyKey]

    @inlinable public init(destkey: ValkeyKey, sourcekeys: [ValkeyKey] = []) {
        self.destkey = destkey
        self.sourcekeys = sourcekeys
    }

    public var keysAffected: [ValkeyKey] { sourcekeys + [destkey] }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("PFMERGE", destkey, sourcekeys)
    }
}

@available(valkeySwift 1.0, *)
extension ValkeyClientProtocol {
    /// Adds elements to a HyperLogLog key. Creates the key if it doesn't exist.
    ///
    /// - Documentation: [PFADD](https://valkey.io/commands/pfadd)
    /// - Available: 2.8.9
    /// - Complexity: O(1) to add every element.
    /// - Response: One of the following
    ///     * 1: If at least 1 HyperLogLog internal register was altered.
    ///     * 0: If no HyperLogLog internal register were altered.
    @inlinable
    @discardableResult
    public func pfadd(_ key: ValkeyKey, elements: [String] = []) async throws -> Int {
        try await execute(PFADD(key, elements: elements))
    }

    /// Returns the approximated cardinality of the set(s) observed by the HyperLogLog key(s).
    ///
    /// - Documentation: [PFCOUNT](https://valkey.io/commands/pfcount)
    /// - Available: 2.8.9
    /// - Complexity: O(1) with a very small average constant time when called with a single key. O(N) with N being the number of keys, and much bigger constant times, when called with multiple keys.
    /// - Response: [Integer]: The approximated number of unique elements observed via PFADD
    @inlinable
    public func pfcount(keys: [ValkeyKey]) async throws -> Int {
        try await execute(PFCOUNT(keys: keys))
    }

    /// Merges one or more HyperLogLog values into a single key.
    ///
    /// - Documentation: [PFMERGE](https://valkey.io/commands/pfmerge)
    /// - Available: 2.8.9
    /// - Complexity: O(N) to merge N HyperLogLogs, but with high constant times.
    @inlinable
    public func pfmerge(destkey: ValkeyKey, sourcekeys: [ValkeyKey] = []) async throws {
        _ = try await execute(PFMERGE(destkey: destkey, sourcekeys: sourcekeys))
    }

}
