//===----------------------------------------------------------------------===//
//
// This source file is part of the valkey-swift open source project
//
// Copyright (c) 2025 the valkey-swift project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of valkey-swift project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// This file is autogenerated by ValkeyCommandsBuilder

import NIOCore

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

/// A container for Sentinel commands.
@_documentation(visibility: internal)
public enum SENTINEL {
    /// Checks for a Sentinel quorum.
    @_documentation(visibility: internal)
    public struct CKQUORUM<PrimaryName: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = ByteBuffer

        @inlinable public static var name: String { "SENTINEL CKQUORUM" }

        public var primaryName: PrimaryName

        @inlinable public init(primaryName: PrimaryName) {
            self.primaryName = primaryName
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "CKQUORUM", RESPBulkString(primaryName))
        }
    }

    /// Configures Sentinel.
    @_documentation(visibility: internal)
    public struct CONFIG: ValkeyCommand {
        public struct ActionSet: RESPRenderable, Sendable, Hashable {
            @usableFromInline let parameter: String
            @usableFromInline let value: String

            @inlinable public init(parameter: String, value: String) {
                self.parameter = parameter
                self.value = value
            }

            @inlinable
            public var respEntries: Int {
                parameter.respEntries + value.respEntries
            }

            @inlinable
            public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
                parameter.encode(into: &commandEncoder)
                value.encode(into: &commandEncoder)
            }
        }
        public enum Action: RESPRenderable, Sendable, Hashable {
            case sets([ActionSet])
            case parameters([String])

            @inlinable
            public var respEntries: Int {
                switch self {
                case .sets(let sets): RESPWithToken("SET", sets).respEntries
                case .parameters(let parameters): RESPWithToken("GET", parameters).respEntries
                }
            }

            @inlinable
            public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
                switch self {
                case .sets(let sets): RESPWithToken("SET", sets).encode(into: &commandEncoder)
                case .parameters(let parameters): RESPWithToken("GET", parameters).encode(into: &commandEncoder)
                }
            }
        }
        public typealias Response = RESPToken.Map?

        @inlinable public static var name: String { "SENTINEL CONFIG" }

        public var action: Action

        @inlinable public init(action: Action) {
            self.action = action
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "CONFIG", action)
        }
    }

    /// Lists or updates the current configurable parameters of Sentinel.
    @_documentation(visibility: internal)
    public struct DEBUG: ValkeyCommand {
        public struct Data: RESPRenderable, Sendable, Hashable {
            @usableFromInline let parameter: String
            @usableFromInline let value: String

            @inlinable public init(parameter: String, value: String) {
                self.parameter = parameter
                self.value = value
            }

            @inlinable
            public var respEntries: Int {
                parameter.respEntries + value.respEntries
            }

            @inlinable
            public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
                parameter.encode(into: &commandEncoder)
                value.encode(into: &commandEncoder)
            }
        }
        public typealias Response = RESPToken.Map?

        @inlinable public static var name: String { "SENTINEL DEBUG" }

        public var data: [Data]

        @inlinable public init(data: [Data] = []) {
            self.data = data
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "DEBUG", data)
        }
    }

    /// Forces a Sentinel failover.
    @_documentation(visibility: internal)
    public struct FAILOVER<PrimaryName: RESPStringRenderable>: ValkeyCommand {
        @inlinable public static var name: String { "SENTINEL FAILOVER" }

        public var primaryName: PrimaryName
        public var coordinated: Bool

        @inlinable public init(primaryName: PrimaryName, coordinated: Bool = false) {
            self.primaryName = primaryName
            self.coordinated = coordinated
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "FAILOVER", RESPBulkString(primaryName), RESPPureToken("COORDINATED", coordinated))
        }
    }

    /// Rewrites the Sentinel configuration file.
    @_documentation(visibility: internal)
    public struct FLUSHCONFIG: ValkeyCommand {
        @inlinable public static var name: String { "SENTINEL FLUSHCONFIG" }

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "FLUSHCONFIG")
        }
    }

    /// Returns the port and address of a primary instance.
    @_documentation(visibility: internal)
    public struct GETMASTERADDRBYNAME<PrimaryName: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL GET-MASTER-ADDR-BY-NAME" }

        public var primaryName: PrimaryName

        @inlinable public init(primaryName: PrimaryName) {
            self.primaryName = primaryName
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "GET-MASTER-ADDR-BY-NAME", RESPBulkString(primaryName))
        }
    }

    /// Returns the port and address of a primary instance.
    @_documentation(visibility: internal)
    public struct GETPRIMARYADDRBYNAME<PrimaryName: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL GET-PRIMARY-ADDR-BY-NAME" }

        public var primaryName: PrimaryName

        @inlinable public init(primaryName: PrimaryName) {
            self.primaryName = primaryName
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "GET-PRIMARY-ADDR-BY-NAME", RESPBulkString(primaryName))
        }
    }

    /// Returns helpful text about the different subcommands.
    @_documentation(visibility: internal)
    public struct HELP: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL HELP" }

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "HELP")
        }
    }

    /// Returns the cached `INFO` replies from the deployment's instances.
    @_documentation(visibility: internal)
    public struct INFOCACHE<Nodename: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL INFO-CACHE" }

        public var nodenames: [Nodename]

        @inlinable public init(nodenames: [Nodename]) {
            self.nodenames = nodenames
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "INFO-CACHE", nodenames.map { RESPBulkString($0) })
        }
    }

    /// Determines whether a primary instance is down.
    @_documentation(visibility: internal)
    public struct ISMASTERDOWNBYADDR<Ip: RESPStringRenderable, Runid: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL IS-MASTER-DOWN-BY-ADDR" }

        public var ip: Ip
        public var port: Int
        public var currentEpoch: Int
        public var runid: Runid

        @inlinable public init(ip: Ip, port: Int, currentEpoch: Int, runid: Runid) {
            self.ip = ip
            self.port = port
            self.currentEpoch = currentEpoch
            self.runid = runid
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "IS-MASTER-DOWN-BY-ADDR", RESPBulkString(ip), port, currentEpoch, RESPBulkString(runid))
        }
    }

    /// Determines whether a primary instance is down.
    @_documentation(visibility: internal)
    public struct ISPRIMARYDOWNBYADDR<Ip: RESPStringRenderable, Runid: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL IS-PRIMARY-DOWN-BY-ADDR" }

        public var ip: Ip
        public var port: Int
        public var currentEpoch: Int
        public var runid: Runid

        @inlinable public init(ip: Ip, port: Int, currentEpoch: Int, runid: Runid) {
            self.ip = ip
            self.port = port
            self.currentEpoch = currentEpoch
            self.runid = runid
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "IS-PRIMARY-DOWN-BY-ADDR", RESPBulkString(ip), port, currentEpoch, RESPBulkString(runid))
        }
    }

    /// Returns the state of a primary instance.
    @_documentation(visibility: internal)
    public struct MASTER<PrimaryName: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Map

        @inlinable public static var name: String { "SENTINEL MASTER" }

        public var primaryName: PrimaryName

        @inlinable public init(primaryName: PrimaryName) {
            self.primaryName = primaryName
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "MASTER", RESPBulkString(primaryName))
        }
    }

    /// Returns a list of monitored primaries.
    @_documentation(visibility: internal)
    public struct MASTERS: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL MASTERS" }

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "MASTERS")
        }
    }

    /// Starts monitoring.
    @_documentation(visibility: internal)
    public struct MONITOR<Name: RESPStringRenderable, Ip: RESPStringRenderable>: ValkeyCommand {
        @inlinable public static var name: String { "SENTINEL MONITOR" }

        public var name: Name
        public var ip: Ip
        public var port: Int
        public var quorum: Int

        @inlinable public init(name: Name, ip: Ip, port: Int, quorum: Int) {
            self.name = name
            self.ip = ip
            self.port = port
            self.quorum = quorum
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "MONITOR", RESPBulkString(name), RESPBulkString(ip), port, quorum)
        }
    }

    /// Returns the Sentinel instance ID.
    @_documentation(visibility: internal)
    public struct MYID: ValkeyCommand {
        public typealias Response = ByteBuffer

        @inlinable public static var name: String { "SENTINEL MYID" }

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "MYID")
        }
    }

    /// Returns information about pending scripts for Sentinel.
    @_documentation(visibility: internal)
    public struct PENDINGSCRIPTS: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL PENDING-SCRIPTS" }

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "PENDING-SCRIPTS")
        }
    }

    /// Returns a list of monitored primaries.
    @_documentation(visibility: internal)
    public struct PRIMARIES: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL PRIMARIES" }

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "PRIMARIES")
        }
    }

    /// Returns the state of a primary instance.
    @_documentation(visibility: internal)
    public struct PRIMARY<PrimaryName: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Map

        @inlinable public static var name: String { "SENTINEL PRIMARY" }

        public var primaryName: PrimaryName

        @inlinable public init(primaryName: PrimaryName) {
            self.primaryName = primaryName
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "PRIMARY", RESPBulkString(primaryName))
        }
    }

    /// Stops monitoring.
    @_documentation(visibility: internal)
    public struct REMOVE<PrimaryName: RESPStringRenderable>: ValkeyCommand {
        @inlinable public static var name: String { "SENTINEL REMOVE" }

        public var primaryName: PrimaryName

        @inlinable public init(primaryName: PrimaryName) {
            self.primaryName = primaryName
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "REMOVE", RESPBulkString(primaryName))
        }
    }

    /// Returns a list of the monitored replicas.
    @_documentation(visibility: internal)
    public struct REPLICAS<PrimaryName: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL REPLICAS" }

        public var primaryName: PrimaryName

        @inlinable public init(primaryName: PrimaryName) {
            self.primaryName = primaryName
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "REPLICAS", RESPBulkString(primaryName))
        }
    }

    /// Resets primaries by name matching a pattern.
    @_documentation(visibility: internal)
    public struct RESET: ValkeyCommand {
        public typealias Response = Int

        @inlinable public static var name: String { "SENTINEL RESET" }

        public var pattern: String

        @inlinable public init(pattern: String) {
            self.pattern = pattern
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "RESET", pattern)
        }
    }

    /// Returns a list of Sentinel instances.
    @_documentation(visibility: internal)
    public struct SENTINELS<PrimaryName: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL SENTINELS" }

        public var primaryName: PrimaryName

        @inlinable public init(primaryName: PrimaryName) {
            self.primaryName = primaryName
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "SENTINELS", RESPBulkString(primaryName))
        }
    }

    /// Changes the configuration of a monitored primary.
    @_documentation(visibility: internal)
    public struct SET<PrimaryName: RESPStringRenderable, Option: RESPStringRenderable, Value: RESPStringRenderable>: ValkeyCommand {
        public struct Data: RESPRenderable, Sendable, Hashable {
            @usableFromInline let option: Option
            @usableFromInline let value: Value

            @inlinable public init(option: Option, value: Value) {
                self.option = option
                self.value = value
            }

            @inlinable
            public var respEntries: Int {
                RESPBulkString(option).respEntries + RESPBulkString(value).respEntries
            }

            @inlinable
            public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
                RESPBulkString(option).encode(into: &commandEncoder)
                RESPBulkString(value).encode(into: &commandEncoder)
            }
        }
        @inlinable public static var name: String { "SENTINEL SET" }

        public var primaryName: PrimaryName
        public var data: [Data]

        @inlinable public init(primaryName: PrimaryName, data: [Data]) {
            self.primaryName = primaryName
            self.data = data
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "SET", RESPBulkString(primaryName), data)
        }
    }

    /// Simulates failover scenarios.
    @_documentation(visibility: internal)
    public struct SIMULATEFAILURE: ValkeyCommand {
        public enum Mode: RESPRenderable, Sendable, Hashable {
            case crashAfterElection
            case crashAfterPromotion
            case help

            @inlinable
            public var respEntries: Int { 1 }

            @inlinable
            public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
                switch self {
                case .crashAfterElection: "crash-after-election".encode(into: &commandEncoder)
                case .crashAfterPromotion: "crash-after-promotion".encode(into: &commandEncoder)
                case .help: "help".encode(into: &commandEncoder)
                }
            }
        }
        public typealias Response = RESPToken.Array?

        @inlinable public static var name: String { "SENTINEL SIMULATE-FAILURE" }

        public var modes: [Mode]

        @inlinable public init(modes: [Mode] = []) {
            self.modes = modes
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "SIMULATE-FAILURE", modes)
        }
    }

    /// Returns a list of the monitored replicas.
    @_documentation(visibility: internal)
    public struct SLAVES<PrimaryName: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public static var name: String { "SENTINEL SLAVES" }

        public var primaryName: PrimaryName

        @inlinable public init(primaryName: PrimaryName) {
            self.primaryName = primaryName
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SENTINEL", "SLAVES", RESPBulkString(primaryName))
        }
    }

}

extension ValkeyClientProtocol {
    /// Checks for a Sentinel quorum.
    ///
    /// - Documentation: [SENTINEL CKQUORUM](https://valkey.io/commands/sentinel-ckquorum)
    /// - Available: 2.8.4
    /// - Response: [String]: Returns OK if the current Sentinel configuration is able to reach the quorum needed to failover a primary, and the majority needed to authorize the failover.
    @inlinable
    @discardableResult
    public func sentinelCkquorum<PrimaryName: RESPStringRenderable>(primaryName: PrimaryName) async throws -> ByteBuffer {
        try await execute(SENTINEL.CKQUORUM(primaryName: primaryName))
    }

    /// Configures Sentinel.
    ///
    /// - Documentation: [SENTINEL CONFIG](https://valkey.io/commands/sentinel-config)
    /// - Available: 6.2.0
    /// - History:
    ///     * 7.2.0: Added the ability to set and get multiple parameters in one call.
    /// - Complexity: O(N) when N is the number of configuration parameters provided
    /// - Response: One of the following
    ///     * [Map]: When 'SENTINEL-CONFIG GET' is called, returns a map.
    ///     * "OK": When 'SENTINEL-CONFIG SET' is called, returns OK on success.
    @inlinable
    @discardableResult
    public func sentinelConfig(action: SENTINEL.CONFIG.Action) async throws -> RESPToken.Map? {
        try await execute(SENTINEL.CONFIG(action: action))
    }

    /// Lists or updates the current configurable parameters of Sentinel.
    ///
    /// - Documentation: [SENTINEL DEBUG](https://valkey.io/commands/sentinel-debug)
    /// - Available: 7.0.0
    /// - Complexity: O(N) where N is the number of configurable parameters
    /// - Response: One of the following
    ///     * "OK": The configuration update was successful.
    ///     * [Map]: List of configurable time parameters and their values (milliseconds).
    @inlinable
    @discardableResult
    public func sentinelDebug(data: [SENTINEL.DEBUG.Data] = []) async throws -> RESPToken.Map? {
        try await execute(SENTINEL.DEBUG(data: data))
    }

    /// Forces a Sentinel failover.
    ///
    /// - Documentation: [SENTINEL FAILOVER](https://valkey.io/commands/sentinel-failover)
    /// - Available: 2.8.4
    /// - History:
    ///     * 9.0.0: `COORDINATED` option.
    /// - Response: "OK": Force a fail over of the primary. Without options, the fail over is executed immediately as if the primary was not reachable. Using `COORDINATED`, fail over seeking agreement from other Sentinels and using coordinated fail over.
    @inlinable
    public func sentinelFailover<PrimaryName: RESPStringRenderable>(primaryName: PrimaryName, coordinated: Bool = false) async throws {
        _ = try await execute(SENTINEL.FAILOVER(primaryName: primaryName, coordinated: coordinated))
    }

    /// Rewrites the Sentinel configuration file.
    ///
    /// - Documentation: [SENTINEL FLUSHCONFIG](https://valkey.io/commands/sentinel-flushconfig)
    /// - Available: 2.8.4
    /// - Complexity: O(1)
    /// - Response: "OK": Force Sentinel to rewrite its configuration on disk, including the current Sentinel state.
    @inlinable
    public func sentinelFlushconfig() async throws {
        _ = try await execute(SENTINEL.FLUSHCONFIG())
    }

    /// Returns the port and address of a primary instance.
    ///
    /// - Documentation: [SENTINEL GET-MASTER-ADDR-BY-NAME](https://valkey.io/commands/sentinel-get-master-addr-by-name)
    /// - Available: 2.8.4
    /// - Deprecated since: 8.0.0. Replaced by `SENTINEL GET-PRIMARY-ADDR-BY-NAME`.
    /// - Complexity: O(1)
    /// - Response: [Array]: IP addr or hostname.
    @inlinable
    @discardableResult
    public func sentinelGetMasterAddrByName<PrimaryName: RESPStringRenderable>(primaryName: PrimaryName) async throws -> RESPToken.Array {
        try await execute(SENTINEL.GETMASTERADDRBYNAME(primaryName: primaryName))
    }

    /// Returns the port and address of a primary instance.
    ///
    /// - Documentation: [SENTINEL GET-PRIMARY-ADDR-BY-NAME](https://valkey.io/commands/sentinel-get-primary-addr-by-name)
    /// - Available: 8.0.0
    /// - Complexity: O(1)
    /// - Response: [Array]: IP addr or hostname.
    @inlinable
    @discardableResult
    public func sentinelGetPrimaryAddrByName<PrimaryName: RESPStringRenderable>(primaryName: PrimaryName) async throws -> RESPToken.Array {
        try await execute(SENTINEL.GETPRIMARYADDRBYNAME(primaryName: primaryName))
    }

    /// Returns helpful text about the different subcommands.
    ///
    /// - Documentation: [SENTINEL HELP](https://valkey.io/commands/sentinel-help)
    /// - Available: 6.2.0
    /// - Complexity: O(1)
    /// - Response: [Array]: Helpful text about subcommands.
    @inlinable
    @discardableResult
    public func sentinelHelp() async throws -> RESPToken.Array {
        try await execute(SENTINEL.HELP())
    }

    /// Returns the cached `INFO` replies from the deployment's instances.
    ///
    /// - Documentation: [SENTINEL INFO-CACHE](https://valkey.io/commands/sentinel-info-cache)
    /// - Available: 3.2.0
    /// - Complexity: O(N) where N is the number of instances
    /// - Response: [Array]: This is actually a map, the odd entries are a primary name, and the even entries are the last cached INFO output from that primary and all its replicas.
    @inlinable
    @discardableResult
    public func sentinelInfoCache<Nodename: RESPStringRenderable>(nodenames: [Nodename]) async throws -> RESPToken.Array {
        try await execute(SENTINEL.INFOCACHE(nodenames: nodenames))
    }

    /// Determines whether a primary instance is down.
    ///
    /// - Documentation: [SENTINEL IS-MASTER-DOWN-BY-ADDR](https://valkey.io/commands/sentinel-is-master-down-by-addr)
    /// - Available: 2.8.4
    /// - Deprecated since: 8.0.0. Replaced by `SENTINEL IS-PRIMARY-DOWN-BY-ADDR`.
    /// - Complexity: O(1)
    /// - Response: One of the following
    ///     * [Array]: Primary is up.
    ///     * [Array]: Primary is down.
    @inlinable
    @discardableResult
    public func sentinelIsMasterDownByAddr<Ip: RESPStringRenderable, Runid: RESPStringRenderable>(
        ip: Ip,
        port: Int,
        currentEpoch: Int,
        runid: Runid
    ) async throws -> RESPToken.Array {
        try await execute(SENTINEL.ISMASTERDOWNBYADDR(ip: ip, port: port, currentEpoch: currentEpoch, runid: runid))
    }

    /// Determines whether a primary instance is down.
    ///
    /// - Documentation: [SENTINEL IS-PRIMARY-DOWN-BY-ADDR](https://valkey.io/commands/sentinel-is-primary-down-by-addr)
    /// - Available: 8.0.0
    /// - Complexity: O(1)
    /// - Response: One of the following
    ///     * [Array]: Primary is up.
    ///     * [Array]: Primary is down.
    @inlinable
    @discardableResult
    public func sentinelIsPrimaryDownByAddr<Ip: RESPStringRenderable, Runid: RESPStringRenderable>(
        ip: Ip,
        port: Int,
        currentEpoch: Int,
        runid: Runid
    ) async throws -> RESPToken.Array {
        try await execute(SENTINEL.ISPRIMARYDOWNBYADDR(ip: ip, port: port, currentEpoch: currentEpoch, runid: runid))
    }

    /// Returns the state of a primary instance.
    ///
    /// - Documentation: [SENTINEL MASTER](https://valkey.io/commands/sentinel-master)
    /// - Available: 2.8.4
    /// - Deprecated since: 8.0.0. Replaced by `SENTINEL PRIMARY`.
    /// - Complexity: O(1)
    /// - Response: [Map]: The state and info of the specified primary.
    @inlinable
    @discardableResult
    public func sentinelMaster<PrimaryName: RESPStringRenderable>(primaryName: PrimaryName) async throws -> RESPToken.Map {
        try await execute(SENTINEL.MASTER(primaryName: primaryName))
    }

    /// Returns a list of monitored primaries.
    ///
    /// - Documentation: [SENTINEL MASTERS](https://valkey.io/commands/sentinel-masters)
    /// - Available: 2.8.4
    /// - Deprecated since: 8.0.0. Replaced by `SENTINEL PRIMARIES`.
    /// - Complexity: O(N) where N is the number of primaries
    /// - Response: [Array]: List of monitored primaries, and their states.
    @inlinable
    @discardableResult
    public func sentinelMasters() async throws -> RESPToken.Array {
        try await execute(SENTINEL.MASTERS())
    }

    /// Starts monitoring.
    ///
    /// - Documentation: [SENTINEL MONITOR](https://valkey.io/commands/sentinel-monitor)
    /// - Available: 2.8.4
    /// - Complexity: O(1)
    @inlinable
    public func sentinelMonitor<Name: RESPStringRenderable, Ip: RESPStringRenderable>(name: Name, ip: Ip, port: Int, quorum: Int) async throws {
        _ = try await execute(SENTINEL.MONITOR(name: name, ip: ip, port: port, quorum: quorum))
    }

    /// Returns the Sentinel instance ID.
    ///
    /// - Documentation: [SENTINEL MYID](https://valkey.io/commands/sentinel-myid)
    /// - Available: 6.2.0
    /// - Complexity: O(1)
    /// - Response: [String]: Node ID of the sentinel instance.
    @inlinable
    @discardableResult
    public func sentinelMyid() async throws -> ByteBuffer {
        try await execute(SENTINEL.MYID())
    }

    /// Returns information about pending scripts for Sentinel.
    ///
    /// - Documentation: [SENTINEL PENDING-SCRIPTS](https://valkey.io/commands/sentinel-pending-scripts)
    /// - Available: 2.8.4
    /// - Response: [Array]: List of pending scripts.
    @inlinable
    @discardableResult
    public func sentinelPendingScripts() async throws -> RESPToken.Array {
        try await execute(SENTINEL.PENDINGSCRIPTS())
    }

    /// Returns a list of monitored primaries.
    ///
    /// - Documentation: [SENTINEL PRIMARIES](https://valkey.io/commands/sentinel-primaries)
    /// - Available: 8.0.0
    /// - Complexity: O(N) where N is the number of primaries
    /// - Response: [Array]: List of monitored primaries, and their states.
    @inlinable
    @discardableResult
    public func sentinelPrimaries() async throws -> RESPToken.Array {
        try await execute(SENTINEL.PRIMARIES())
    }

    /// Returns the state of a primary instance.
    ///
    /// - Documentation: [SENTINEL PRIMARY](https://valkey.io/commands/sentinel-primary)
    /// - Available: 8.0.0
    /// - Complexity: O(1)
    /// - Response: [Map]: The state and info of the specified primary.
    @inlinable
    @discardableResult
    public func sentinelPrimary<PrimaryName: RESPStringRenderable>(primaryName: PrimaryName) async throws -> RESPToken.Map {
        try await execute(SENTINEL.PRIMARY(primaryName: primaryName))
    }

    /// Stops monitoring.
    ///
    /// - Documentation: [SENTINEL REMOVE](https://valkey.io/commands/sentinel-remove)
    /// - Available: 2.8.4
    /// - Complexity: O(1)
    @inlinable
    public func sentinelRemove<PrimaryName: RESPStringRenderable>(primaryName: PrimaryName) async throws {
        _ = try await execute(SENTINEL.REMOVE(primaryName: primaryName))
    }

    /// Returns a list of the monitored replicas.
    ///
    /// - Documentation: [SENTINEL REPLICAS](https://valkey.io/commands/sentinel-replicas)
    /// - Available: 5.0.0
    /// - Complexity: O(N) where N is the number of replicas
    /// - Response: [Array]: List of replicas for this primary, and their state.
    @inlinable
    @discardableResult
    public func sentinelReplicas<PrimaryName: RESPStringRenderable>(primaryName: PrimaryName) async throws -> RESPToken.Array {
        try await execute(SENTINEL.REPLICAS(primaryName: primaryName))
    }

    /// Resets primaries by name matching a pattern.
    ///
    /// - Documentation: [SENTINEL RESET](https://valkey.io/commands/sentinel-reset)
    /// - Available: 2.8.4
    /// - Complexity: O(N) where N is the number of monitored primaries
    /// - Response: [Integer]: The number of primaries that were reset.
    @inlinable
    @discardableResult
    public func sentinelReset(pattern: String) async throws -> Int {
        try await execute(SENTINEL.RESET(pattern: pattern))
    }

    /// Returns a list of Sentinel instances.
    ///
    /// - Documentation: [SENTINEL SENTINELS](https://valkey.io/commands/sentinel-sentinels)
    /// - Available: 2.8.4
    /// - Complexity: O(N) where N is the number of Sentinels
    /// - Response: [Array]: List of sentinel instances, and their state.
    @inlinable
    @discardableResult
    public func sentinelSentinels<PrimaryName: RESPStringRenderable>(primaryName: PrimaryName) async throws -> RESPToken.Array {
        try await execute(SENTINEL.SENTINELS(primaryName: primaryName))
    }

    /// Changes the configuration of a monitored primary.
    ///
    /// - Documentation: [SENTINEL SET](https://valkey.io/commands/sentinel-set)
    /// - Available: 2.8.4
    /// - Complexity: O(1)
    @inlinable
    public func sentinelSet<PrimaryName: RESPStringRenderable, Option: RESPStringRenderable, Value: RESPStringRenderable>(
        primaryName: PrimaryName,
        data: [SENTINEL.SET<PrimaryName, Option, Value>.Data]
    ) async throws {
        _ = try await execute(SENTINEL.SET(primaryName: primaryName, data: data))
    }

    /// Simulates failover scenarios.
    ///
    /// - Documentation: [SENTINEL SIMULATE-FAILURE](https://valkey.io/commands/sentinel-simulate-failure)
    /// - Available: 3.2.0
    /// - Response: One of the following
    ///     * "OK": The simulated flag was set.
    ///     * [Array]: Supported simulates flags. Returned in case `HELP` was used.
    @inlinable
    @discardableResult
    public func sentinelSimulateFailure(modes: [SENTINEL.SIMULATEFAILURE.Mode] = []) async throws -> RESPToken.Array? {
        try await execute(SENTINEL.SIMULATEFAILURE(modes: modes))
    }

    /// Returns a list of the monitored replicas.
    ///
    /// - Documentation: [SENTINEL SLAVES](https://valkey.io/commands/sentinel-slaves)
    /// - Available: 2.8.0
    /// - Deprecated since: 5.0.0. Replaced by `SENTINEL REPLICAS`.
    /// - Complexity: O(N) where N is the number of replicas.
    /// - Response: [Array]: List of monitored replicas, and their state.
    @inlinable
    @discardableResult
    public func sentinelSlaves<PrimaryName: RESPStringRenderable>(primaryName: PrimaryName) async throws -> RESPToken.Array {
        try await execute(SENTINEL.SLAVES(primaryName: primaryName))
    }

}
