//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-valkey open source project
//
// Copyright (c) 2025 the swift-valkey project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of swift-valkey project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// This file is autogenerated by ValkeyCommandsBuilder

import NIOCore

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

/// A container for Access List Control commands.
public enum ACL {
    /// Lists the ACL categories, or the commands inside a category.
    public struct CAT: ValkeyCommand {
        public typealias Response = RESPToken.Array

        public var category: String?

        @inlinable public init(category: String? = nil) {
            self.category = category
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "CAT", category)
        }
    }

    /// Deletes ACL users, and terminates their connections.
    public struct DELUSER<Username: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = Int

        public var username: [Username]

        @inlinable public init(username: [Username]) {
            self.username = username
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "DELUSER", username.map { RESPBulkString($0) })
        }
    }

    /// Simulates the execution of a command by a user, without executing the command.
    public struct DRYRUN<Username: RESPStringRenderable, Command: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken?

        public var username: Username
        public var command: Command
        public var arg: [String]

        @inlinable public init(username: Username, command: Command, arg: [String] = []) {
            self.username = username
            self.command = command
            self.arg = arg
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "DRYRUN", RESPBulkString(username), RESPBulkString(command), arg)
        }
    }

    /// Generates a pseudorandom, secure password that can be used to identify ACL users.
    public struct GENPASS: ValkeyCommand {
        public var bits: Int?

        @inlinable public init(bits: Int? = nil) {
            self.bits = bits
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "GENPASS", bits)
        }
    }

    /// Lists the ACL rules of a user.
    public struct GETUSER<Username: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Map?

        public var username: Username

        @inlinable public init(username: Username) {
            self.username = username
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "GETUSER", RESPBulkString(username))
        }
    }

    /// Returns helpful text about the different subcommands.
    public struct HELP: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "HELP")
        }
    }

    /// Dumps the effective rules in ACL file format.
    public struct LIST: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "LIST")
        }
    }

    /// Reloads the rules from the configured ACL file.
    public struct LOAD: ValkeyCommand {
        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "LOAD")
        }
    }

    /// Lists recent security events generated due to ACL rules.
    public struct LOG: ValkeyCommand {
        public enum Operation: RESPRenderable, Sendable {
            case count(Int)
            case reset

            @inlinable
            public var respEntries: Int {
                switch self {
                case .count(let count): count.respEntries
                case .reset: "RESET".respEntries
                }
            }

            @inlinable
            public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
                switch self {
                case .count(let count): count.encode(into: &commandEncoder)
                case .reset: "RESET".encode(into: &commandEncoder)
                }
            }
        }
        public typealias Response = RESPToken.Array?

        public var operation: Operation?

        @inlinable public init(operation: Operation? = nil) {
            self.operation = operation
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "LOG", operation)
        }
    }

    /// Saves the effective ACL rules in the configured ACL file.
    public struct SAVE: ValkeyCommand {
        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "SAVE")
        }
    }

    /// Creates and modifies an ACL user and its rules.
    public struct SETUSER<Username: RESPStringRenderable>: ValkeyCommand {
        public var username: Username
        public var rule: [String]

        @inlinable public init(username: Username, rule: [String] = []) {
            self.username = username
            self.rule = rule
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "SETUSER", RESPBulkString(username), rule)
        }
    }

    /// Lists all ACL users.
    public struct USERS: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "USERS")
        }
    }

    /// Returns the authenticated username of the current connection.
    public struct WHOAMI: ValkeyCommand {
        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("ACL", "WHOAMI")
        }
    }

}

extension COMMAND {
    /// Returns a count of commands.
    public struct COUNT: ValkeyCommand {
        public typealias Response = Int

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("COMMAND", "COUNT")
        }
    }

    /// Returns documentary information about one, multiple or all commands.
    public struct DOCS: ValkeyCommand {
        public typealias Response = RESPToken.Map

        public var commandName: [String]

        @inlinable public init(commandName: [String] = []) {
            self.commandName = commandName
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("COMMAND", "DOCS", commandName)
        }
    }

    /// Extracts the key names from an arbitrary command.
    public struct GETKEYS<Command: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Array

        public var command: Command
        public var arg: [String]

        @inlinable public init(command: Command, arg: [String] = []) {
            self.command = command
            self.arg = arg
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("COMMAND", "GETKEYS", RESPBulkString(command), arg)
        }
    }

    /// Extracts the key names and access flags for an arbitrary command.
    public struct GETKEYSANDFLAGS<Command: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Array

        public var command: Command
        public var arg: [String]

        @inlinable public init(command: Command, arg: [String] = []) {
            self.command = command
            self.arg = arg
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("COMMAND", "GETKEYSANDFLAGS", RESPBulkString(command), arg)
        }
    }

    /// Returns helpful text about the different subcommands.
    public struct HELP: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("COMMAND", "HELP")
        }
    }

    /// Returns information about one, multiple or all commands.
    public struct INFO: ValkeyCommand {
        public typealias Response = RESPToken.Array

        public var commandName: [String]

        @inlinable public init(commandName: [String] = []) {
            self.commandName = commandName
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("COMMAND", "INFO", commandName)
        }
    }

    /// Returns a list of command names.
    public struct LIST: ValkeyCommand {
        public enum Filterby: RESPRenderable, Sendable {
            case moduleName(String)
            case category(String)
            case pattern(String)

            @inlinable
            public var respEntries: Int {
                switch self {
                case .moduleName(let moduleName): RESPWithToken("MODULE", moduleName).respEntries
                case .category(let category): RESPWithToken("ACLCAT", category).respEntries
                case .pattern(let pattern): RESPWithToken("PATTERN", pattern).respEntries
                }
            }

            @inlinable
            public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
                switch self {
                case .moduleName(let moduleName): RESPWithToken("MODULE", moduleName).encode(into: &commandEncoder)
                case .category(let category): RESPWithToken("ACLCAT", category).encode(into: &commandEncoder)
                case .pattern(let pattern): RESPWithToken("PATTERN", pattern).encode(into: &commandEncoder)
                }
            }
        }
        public typealias Response = RESPToken.Array

        public var filterby: Filterby?

        @inlinable public init(filterby: Filterby? = nil) {
            self.filterby = filterby
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("COMMAND", "LIST", RESPWithToken("FILTERBY", filterby))
        }
    }

}

/// A container for server configuration commands.
public enum CONFIG {
    /// Returns the effective values of configuration parameters.
    public struct GET<Parameter: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Map

        public var parameter: [Parameter]

        @inlinable public init(parameter: [Parameter]) {
            self.parameter = parameter
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("CONFIG", "GET", parameter.map { RESPBulkString($0) })
        }
    }

    /// Returns helpful text about the different subcommands.
    public struct HELP: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("CONFIG", "HELP")
        }
    }

    /// Resets the server's statistics.
    public struct RESETSTAT: ValkeyCommand {
        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("CONFIG", "RESETSTAT")
        }
    }

    /// Persists the effective configuration to file.
    public struct REWRITE: ValkeyCommand {
        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("CONFIG", "REWRITE")
        }
    }

    /// Sets configuration parameters in-flight.
    public struct SET<Parameter: RESPStringRenderable, Value: RESPStringRenderable>: ValkeyCommand {
        public struct Data: RESPRenderable, Sendable {
            @usableFromInline let parameter: Parameter
            @usableFromInline let value: Value


            @inlinable public init(parameter: Parameter, value: Value) {
                self.parameter = parameter
                self.value = value
            }

            @inlinable
            public var respEntries: Int {
                RESPBulkString(parameter).respEntries + RESPBulkString(value).respEntries
            }

            @inlinable
            public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
                RESPBulkString(parameter).encode(into: &commandEncoder)
                RESPBulkString(value).encode(into: &commandEncoder)
            }
        }
        public var data: [Data]

        @inlinable public init(data: [Data]) {
            self.data = data
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("CONFIG", "SET", data)
        }
    }

}

/// A container for latency diagnostics commands.
public enum LATENCY {
    /// Returns a human-readable latency analysis report.
    public struct DOCTOR: ValkeyCommand {
        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("LATENCY", "DOCTOR")
        }
    }

    /// Returns a latency graph for an event.
    public struct GRAPH<Event: RESPStringRenderable>: ValkeyCommand {
        public var event: Event

        @inlinable public init(event: Event) {
            self.event = event
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("LATENCY", "GRAPH", RESPBulkString(event))
        }
    }

    /// Returns helpful text about the different subcommands.
    public struct HELP: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("LATENCY", "HELP")
        }
    }

    /// Returns the cumulative distribution of latencies of a subset or all commands.
    public struct HISTOGRAM: ValkeyCommand {
        public typealias Response = RESPToken.Map

        public var command: [String]

        @inlinable public init(command: [String] = []) {
            self.command = command
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("LATENCY", "HISTOGRAM", command)
        }
    }

    /// Returns timestamp-latency samples for an event.
    public struct HISTORY<Event: RESPStringRenderable>: ValkeyCommand {
        public typealias Response = RESPToken.Array

        public var event: Event

        @inlinable public init(event: Event) {
            self.event = event
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("LATENCY", "HISTORY", RESPBulkString(event))
        }
    }

    /// Returns the latest latency samples for all events.
    public struct LATEST: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("LATENCY", "LATEST")
        }
    }

    /// Resets the latency data for one or more events.
    public struct RESET: ValkeyCommand {
        public typealias Response = Int

        public var event: [String]

        @inlinable public init(event: [String] = []) {
            self.event = event
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("LATENCY", "RESET", event)
        }
    }

}

/// A container for memory diagnostics commands.
public enum MEMORY {
    /// Outputs a memory problems report.
    public struct DOCTOR: ValkeyCommand {
        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("MEMORY", "DOCTOR")
        }
    }

    /// Returns helpful text about the different subcommands.
    public struct HELP: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("MEMORY", "HELP")
        }
    }

    /// Returns the allocator statistics.
    public struct MALLOCSTATS: ValkeyCommand {
        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("MEMORY", "MALLOC-STATS")
        }
    }

    /// Asks the allocator to release memory.
    public struct PURGE: ValkeyCommand {
        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("MEMORY", "PURGE")
        }
    }

    /// Returns details about memory usage.
    public struct STATS: ValkeyCommand {
        public typealias Response = RESPToken.Map

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("MEMORY", "STATS")
        }
    }

    /// Estimates the memory usage of a key.
    public struct USAGE: ValkeyCommand {
        public typealias Response = Int?

        public var key: ValkeyKey
        public var count: Int?

        @inlinable public init(key: ValkeyKey, count: Int? = nil) {
            self.key = key
            self.count = count
        }

        public var keysAffected: CollectionOfOne<ValkeyKey> { .init(key) }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("MEMORY", "USAGE", key, RESPWithToken("SAMPLES", count))
        }
    }

}

/// A container for module commands.
public enum MODULE {
    /// Returns helpful text about the different subcommands.
    public struct HELP: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("MODULE", "HELP")
        }
    }

    /// Returns all loaded modules.
    public struct LIST: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("MODULE", "LIST")
        }
    }

    /// Loads a module.
    public struct LOAD<Path: RESPStringRenderable>: ValkeyCommand {
        public var path: Path
        public var arg: [String]

        @inlinable public init(path: Path, arg: [String] = []) {
            self.path = path
            self.arg = arg
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("MODULE", "LOAD", RESPBulkString(path), arg)
        }
    }

    /// Loads a module using extended parameters.
    public struct LOADEX<Path: RESPStringRenderable>: ValkeyCommand {
        public struct Configs: RESPRenderable, Sendable {
            @usableFromInline let name: String
            @usableFromInline let value: String


            @inlinable public init(name: String, value: String) {
                self.name = name
                self.value = value
            }

            @inlinable
            public var respEntries: Int {
                name.respEntries + value.respEntries
            }

            @inlinable
            public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
                name.encode(into: &commandEncoder)
                value.encode(into: &commandEncoder)
            }
        }
        public var path: Path
        public var configs: [Configs]
        public var args: [String]

        @inlinable public init(path: Path, configs: [Configs] = [], args: [String] = []) {
            self.path = path
            self.configs = configs
            self.args = args
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("MODULE", "LOADEX", RESPBulkString(path), RESPWithToken("CONFIG", configs), RESPWithToken("ARGS", args))
        }
    }

    /// Unloads a module.
    public struct UNLOAD<Name: RESPStringRenderable>: ValkeyCommand {
        public var name: Name

        @inlinable public init(name: Name) {
            self.name = name
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("MODULE", "UNLOAD", RESPBulkString(name))
        }
    }

}

/// A container for slow log commands.
public enum SLOWLOG {
    /// Returns the slow log's entries.
    public struct GET: ValkeyCommand {
        public typealias Response = RESPToken.Array

        public var count: Int?

        @inlinable public init(count: Int? = nil) {
            self.count = count
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SLOWLOG", "GET", count)
        }
    }

    /// Show helpful text about the different subcommands
    public struct HELP: ValkeyCommand {
        public typealias Response = RESPToken.Array

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SLOWLOG", "HELP")
        }
    }

    /// Returns the number of entries in the slow log.
    public struct LEN: ValkeyCommand {
        public typealias Response = Int

        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SLOWLOG", "LEN")
        }
    }

    /// Clears all entries from the slow log.
    public struct RESET: ValkeyCommand {
        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            commandEncoder.encodeArray("SLOWLOG", "RESET")
        }
    }

}

/// Asynchronously rewrites the append-only file to disk.
public struct BGREWRITEAOF: ValkeyCommand {
    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("BGREWRITEAOF")
    }
}

/// Asynchronously saves the database(s) to disk.
public struct BGSAVE: ValkeyCommand {
    public typealias Response = String

    public var schedule: Bool

    @inlinable public init(schedule: Bool = false) {
        self.schedule = schedule
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("BGSAVE", RESPPureToken("SCHEDULE", schedule))
    }
}

/// Returns detailed information about all commands.
public struct COMMAND: ValkeyCommand {
    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("COMMAND")
    }
}

/// Returns the number of keys in the database.
public struct DBSIZE: ValkeyCommand {
    public typealias Response = Int

    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("DBSIZE")
    }
}

/// A container for debugging commands.
public struct DEBUG: ValkeyCommand {
    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("DEBUG")
    }
}

/// Starts a coordinated failover from a server to one of its replicas.
public struct FAILOVER: ValkeyCommand {
    public struct Target: RESPRenderable, Sendable {
        @usableFromInline let host: String
        @usableFromInline let port: Int
        @usableFromInline let force: Bool


        @inlinable public init(host: String, port: Int, force: Bool = false) {
            self.host = host
            self.port = port
            self.force = force
        }

        @inlinable
        public var respEntries: Int {
            host.respEntries + port.respEntries + "FORCE".respEntries
        }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            host.encode(into: &commandEncoder)
            port.encode(into: &commandEncoder)
            "FORCE".encode(into: &commandEncoder)
        }
    }
    public var target: Target?
    public var abort: Bool
    public var milliseconds: Int?

    @inlinable public init(target: Target? = nil, abort: Bool = false, milliseconds: Int? = nil) {
        self.target = target
        self.abort = abort
        self.milliseconds = milliseconds
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("FAILOVER", RESPWithToken("TO", target), RESPPureToken("ABORT", abort), RESPWithToken("TIMEOUT", milliseconds))
    }
}

/// Removes all keys from all databases.
public struct FLUSHALL: ValkeyCommand {
    public enum FlushType: RESPRenderable, Sendable {
        case async
        case sync

        @inlinable
        public var respEntries: Int { 1 }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            switch self {
            case .async: "ASYNC".encode(into: &commandEncoder)
            case .sync: "SYNC".encode(into: &commandEncoder)
            }
        }
    }
    public var flushType: FlushType?

    @inlinable public init(flushType: FlushType? = nil) {
        self.flushType = flushType
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("FLUSHALL", flushType)
    }
}

/// Remove all keys from the current database.
public struct FLUSHDB: ValkeyCommand {
    public enum FlushType: RESPRenderable, Sendable {
        case async
        case sync

        @inlinable
        public var respEntries: Int { 1 }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            switch self {
            case .async: "ASYNC".encode(into: &commandEncoder)
            case .sync: "SYNC".encode(into: &commandEncoder)
            }
        }
    }
    public var flushType: FlushType?

    @inlinable public init(flushType: FlushType? = nil) {
        self.flushType = flushType
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("FLUSHDB", flushType)
    }
}

/// Returns information and statistics about the server.
public struct INFO: ValkeyCommand {
    public var section: [String]

    @inlinable public init(section: [String] = []) {
        self.section = section
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("INFO", section)
    }
}

/// Returns the Unix timestamp of the last successful save to disk.
public struct LASTSAVE: ValkeyCommand {
    public typealias Response = Int

    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("LASTSAVE")
    }
}

/// Displays computer art and the server version
public struct LOLWUT: ValkeyCommand {
    public var version: Int?

    @inlinable public init(version: Int? = nil) {
        self.version = version
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("LOLWUT", RESPWithToken("VERSION", version))
    }
}

/// Listens for all requests received by the server in real-time.
public struct MONITOR: ValkeyCommand {
    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("MONITOR")
    }
}

/// An internal command used in replication.
public struct PSYNC<Replicationid: RESPStringRenderable>: ValkeyCommand {
    public var replicationid: Replicationid
    public var offset: Int

    @inlinable public init(replicationid: Replicationid, offset: Int) {
        self.replicationid = replicationid
        self.offset = offset
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("PSYNC", RESPBulkString(replicationid), offset)
    }
}

/// An internal command for configuring the replication stream.
public struct REPLCONF: ValkeyCommand {
    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("REPLCONF")
    }
}

/// Configures a server as replica of another, or promotes it to a primary.
public struct REPLICAOF: ValkeyCommand {
    public struct ArgsHostPort: RESPRenderable, Sendable {
        @usableFromInline let host: String
        @usableFromInline let port: Int


        @inlinable public init(host: String, port: Int) {
            self.host = host
            self.port = port
        }

        @inlinable
        public var respEntries: Int {
            host.respEntries + port.respEntries
        }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            host.encode(into: &commandEncoder)
            port.encode(into: &commandEncoder)
        }
    }
    public struct ArgsNoOne: RESPRenderable, Sendable {
        @usableFromInline let no: Bool
        @usableFromInline let one: Bool


        @inlinable public init(no: Bool = false, one: Bool = false) {
            self.no = no
            self.one = one
        }

        @inlinable
        public var respEntries: Int {
            "NO".respEntries + "ONE".respEntries
        }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            "NO".encode(into: &commandEncoder)
            "ONE".encode(into: &commandEncoder)
        }
    }
    public enum Args: RESPRenderable, Sendable {
        case hostPort(ArgsHostPort)
        case noOne(ArgsNoOne)

        @inlinable
        public var respEntries: Int {
            switch self {
            case .hostPort(let hostPort): hostPort.respEntries
            case .noOne(let noOne): noOne.respEntries
            }
        }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            switch self {
            case .hostPort(let hostPort): hostPort.encode(into: &commandEncoder)
            case .noOne(let noOne): noOne.encode(into: &commandEncoder)
            }
        }
    }
    public var args: Args

    @inlinable public init(args: Args) {
        self.args = args
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("REPLICAOF", args)
    }
}

/// An internal command for migrating keys in a cluster.
public struct RESTOREASKING<SerializedValue: RESPStringRenderable>: ValkeyCommand {
    public var key: ValkeyKey
    public var ttl: Int
    public var serializedValue: SerializedValue
    public var replace: Bool
    public var absttl: Bool
    public var seconds: Int?
    public var frequency: Int?

    @inlinable public init(key: ValkeyKey, ttl: Int, serializedValue: SerializedValue, replace: Bool = false, absttl: Bool = false, seconds: Int? = nil, frequency: Int? = nil) {
        self.key = key
        self.ttl = ttl
        self.serializedValue = serializedValue
        self.replace = replace
        self.absttl = absttl
        self.seconds = seconds
        self.frequency = frequency
    }

    public var keysAffected: CollectionOfOne<ValkeyKey> { .init(key) }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("RESTORE-ASKING", key, ttl, RESPBulkString(serializedValue), RESPPureToken("REPLACE", replace), RESPPureToken("ABSTTL", absttl), RESPWithToken("IDLETIME", seconds), RESPWithToken("FREQ", frequency))
    }
}

/// Returns the replication role.
public struct ROLE: ValkeyCommand {
    public typealias Response = RESPToken.Array

    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("ROLE")
    }
}

/// Synchronously saves the database(s) to disk.
public struct SAVE: ValkeyCommand {
    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("SAVE")
    }
}

/// Synchronously saves the database(s) to disk and shuts down the server.
public struct SHUTDOWN: ValkeyCommand {
    public enum AbortSelectorSaveSelectorBlockSaveSelector: RESPRenderable, Sendable {
        case nosave
        case save

        @inlinable
        public var respEntries: Int { 1 }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            switch self {
            case .nosave: "NOSAVE".encode(into: &commandEncoder)
            case .save: "SAVE".encode(into: &commandEncoder)
            }
        }
    }
    public struct AbortSelectorSaveSelectorBlock: RESPRenderable, Sendable {
        @usableFromInline let saveSelector: AbortSelectorSaveSelectorBlockSaveSelector?
        @usableFromInline let now: Bool
        @usableFromInline let force: Bool


        @inlinable public init(saveSelector: AbortSelectorSaveSelectorBlockSaveSelector? = nil, now: Bool = false, force: Bool = false) {
            self.saveSelector = saveSelector
            self.now = now
            self.force = force
        }

        @inlinable
        public var respEntries: Int {
            saveSelector.respEntries + "NOW".respEntries + "FORCE".respEntries
        }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            saveSelector.encode(into: &commandEncoder)
            "NOW".encode(into: &commandEncoder)
            "FORCE".encode(into: &commandEncoder)
        }
    }
    public enum AbortSelector: RESPRenderable, Sendable {
        case saveSelectorBlock(AbortSelectorSaveSelectorBlock)
        case abort

        @inlinable
        public var respEntries: Int {
            switch self {
            case .saveSelectorBlock(let saveSelectorBlock): saveSelectorBlock.respEntries
            case .abort: "ABORT".respEntries
            }
        }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            switch self {
            case .saveSelectorBlock(let saveSelectorBlock): saveSelectorBlock.encode(into: &commandEncoder)
            case .abort: "ABORT".encode(into: &commandEncoder)
            }
        }
    }
    public var abortSelector: AbortSelector?

    @inlinable public init(abortSelector: AbortSelector? = nil) {
        self.abortSelector = abortSelector
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("SHUTDOWN", abortSelector)
    }
}

/// Sets a server as a replica of another, or promotes it to being a primary.
@available(*, deprecated, message: "Since 5.0.0. Replaced by `REPLICAOF`.")
public struct SLAVEOF: ValkeyCommand {
    public struct ArgsHostPort: RESPRenderable, Sendable {
        @usableFromInline let host: String
        @usableFromInline let port: Int


        @inlinable public init(host: String, port: Int) {
            self.host = host
            self.port = port
        }

        @inlinable
        public var respEntries: Int {
            host.respEntries + port.respEntries
        }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            host.encode(into: &commandEncoder)
            port.encode(into: &commandEncoder)
        }
    }
    public struct ArgsNoOne: RESPRenderable, Sendable {
        @usableFromInline let no: Bool
        @usableFromInline let one: Bool


        @inlinable public init(no: Bool = false, one: Bool = false) {
            self.no = no
            self.one = one
        }

        @inlinable
        public var respEntries: Int {
            "NO".respEntries + "ONE".respEntries
        }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            "NO".encode(into: &commandEncoder)
            "ONE".encode(into: &commandEncoder)
        }
    }
    public enum Args: RESPRenderable, Sendable {
        case hostPort(ArgsHostPort)
        case noOne(ArgsNoOne)

        @inlinable
        public var respEntries: Int {
            switch self {
            case .hostPort(let hostPort): hostPort.respEntries
            case .noOne(let noOne): noOne.respEntries
            }
        }

        @inlinable
        public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
            switch self {
            case .hostPort(let hostPort): hostPort.encode(into: &commandEncoder)
            case .noOne(let noOne): noOne.encode(into: &commandEncoder)
            }
        }
    }
    public var args: Args

    @inlinable public init(args: Args) {
        self.args = args
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("SLAVEOF", args)
    }
}

/// Swaps two databases.
public struct SWAPDB: ValkeyCommand {
    public var index1: Int
    public var index2: Int

    @inlinable public init(index1: Int, index2: Int) {
        self.index1 = index1
        self.index2 = index2
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("SWAPDB", index1, index2)
    }
}

/// An internal command used in replication.
public struct SYNC: ValkeyCommand {
    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("SYNC")
    }
}

/// Returns the server time.
public struct TIME: ValkeyCommand {
    public typealias Response = RESPToken.Array

    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("TIME")
    }
}

extension ValkeyConnection {
    /// Lists the ACL categories, or the commands inside a category.
    ///
    /// - Documentation: [ACL CAT](https:/valkey.io/commands/acl-cat)
    /// - Available: 6.0.0
    /// - Complexity: O(1) since the categories and commands are a fixed set.
    /// - Returns: One of the following
    ///     * [Array]: In case `category` was not given, a list of existing ACL categories
    ///     * [Array]: In case `category` was given, list of commands that fall under the provided ACL category.
    @inlinable
    public func aclCat(category: String? = nil) async throws -> RESPToken.Array {
        try await send(command: ACL.CAT(category: category))
    }

    /// Deletes ACL users, and terminates their connections.
    ///
    /// - Documentation: [ACL DELUSER](https:/valkey.io/commands/acl-deluser)
    /// - Available: 6.0.0
    /// - Complexity: O(1) amortized time considering the typical user.
    /// - Returns: [Integer]: The number of users that were deleted.
    @inlinable
    public func aclDeluser<Username: RESPStringRenderable>(username: [Username]) async throws -> Int {
        try await send(command: ACL.DELUSER(username: username))
    }

    /// Simulates the execution of a command by a user, without executing the command.
    ///
    /// - Documentation: [ACL DRYRUN](https:/valkey.io/commands/acl-dryrun)
    /// - Available: 7.0.0
    /// - Complexity: O(1).
    /// - Returns: One of the following
    ///     * "OK": The given user may successfully execute the given command.
    ///     * [String]: The description of the problem, in case the user is not allowed to run the given command.
    @inlinable
    public func aclDryrun<Username: RESPStringRenderable, Command: RESPStringRenderable>(username: Username, command: Command, arg: [String] = []) async throws -> RESPToken? {
        try await send(command: ACL.DRYRUN(username: username, command: command, arg: arg))
    }

    /// Generates a pseudorandom, secure password that can be used to identify ACL users.
    ///
    /// - Documentation: [ACL GENPASS](https:/valkey.io/commands/acl-genpass)
    /// - Available: 6.0.0
    /// - Complexity: O(1)
    /// - Returns: [String]: Pseudorandom data. By default it contains 64 bytes, representing 256 bits of data. If `bits` was given, the output string length is the number of specified bits (rounded to the next multiple of 4) divided by 4.
    @inlinable
    public func aclGenpass(bits: Int? = nil) async throws -> ACL.GENPASS.Response {
        try await send(command: ACL.GENPASS(bits: bits))
    }

    /// Lists the ACL rules of a user.
    ///
    /// - Documentation: [ACL GETUSER](https:/valkey.io/commands/acl-getuser)
    /// - Available: 6.0.0
    /// - History:
    ///     * 6.2.0: Added Pub/Sub channel patterns.
    ///     * 7.0.0: Added selectors and changed the format of key and channel patterns from a list to their rule representation.
    /// - Complexity: O(N). Where N is the number of password, command and pattern rules that the user has.
    /// - Returns: One of the following
    ///     * [Map]: A set of ACL rule definitions for the user.
    ///     * [Null]: If user does not exist
    @inlinable
    public func aclGetuser<Username: RESPStringRenderable>(username: Username) async throws -> RESPToken.Map? {
        try await send(command: ACL.GETUSER(username: username))
    }

    /// Returns helpful text about the different subcommands.
    ///
    /// - Documentation: [ACL HELP](https:/valkey.io/commands/acl-help)
    /// - Available: 6.0.0
    /// - Complexity: O(1)
    /// - Returns: [Array]: A list of subcommands and their description.
    @inlinable
    public func aclHelp() async throws -> RESPToken.Array {
        try await send(command: ACL.HELP())
    }

    /// Dumps the effective rules in ACL file format.
    ///
    /// - Documentation: [ACL LIST](https:/valkey.io/commands/acl-list)
    /// - Available: 6.0.0
    /// - Complexity: O(N). Where N is the number of configured users.
    /// - Returns: [Array]: A list of currently active ACL rules.
    @inlinable
    public func aclList() async throws -> RESPToken.Array {
        try await send(command: ACL.LIST())
    }

    /// Reloads the rules from the configured ACL file.
    ///
    /// - Documentation: [ACL LOAD](https:/valkey.io/commands/acl-load)
    /// - Available: 6.0.0
    /// - Complexity: O(N). Where N is the number of configured users.
    @inlinable
    public func aclLoad() async throws {
        _ = try await send(command: ACL.LOAD())
    }

    /// Lists recent security events generated due to ACL rules.
    ///
    /// - Documentation: [ACL LOG](https:/valkey.io/commands/acl-log)
    /// - Available: 6.0.0
    /// - History:
    ///     * 7.2.0: Added entry ID, timestamp created, and timestamp last updated.
    /// - Complexity: O(N) with N being the number of entries shown.
    /// - Returns: One of the following
    ///     * [Array]: In case `RESET` was not given, a list of recent ACL security events.
    ///     * "OK": In case `RESET` was given, OK indicates ACL log was cleared.
    @inlinable
    public func aclLog(operation: ACL.LOG.Operation? = nil) async throws -> RESPToken.Array? {
        try await send(command: ACL.LOG(operation: operation))
    }

    /// Saves the effective ACL rules in the configured ACL file.
    ///
    /// - Documentation: [ACL SAVE](https:/valkey.io/commands/acl-save)
    /// - Available: 6.0.0
    /// - Complexity: O(N). Where N is the number of configured users.
    @inlinable
    public func aclSave() async throws {
        _ = try await send(command: ACL.SAVE())
    }

    /// Creates and modifies an ACL user and its rules.
    ///
    /// - Documentation: [ACL SETUSER](https:/valkey.io/commands/acl-setuser)
    /// - Available: 6.0.0
    /// - History:
    ///     * 6.2.0: Added Pub/Sub channel patterns.
    ///     * 7.0.0: Added selectors and key based permissions.
    /// - Complexity: O(N). Where N is the number of rules provided.
    @inlinable
    public func aclSetuser<Username: RESPStringRenderable>(username: Username, rule: [String] = []) async throws {
        _ = try await send(command: ACL.SETUSER(username: username, rule: rule))
    }

    /// Lists all ACL users.
    ///
    /// - Documentation: [ACL USERS](https:/valkey.io/commands/acl-users)
    /// - Available: 6.0.0
    /// - Complexity: O(N). Where N is the number of configured users.
    /// - Returns: [Array]: List of existing ACL users.
    @inlinable
    public func aclUsers() async throws -> RESPToken.Array {
        try await send(command: ACL.USERS())
    }

    /// Returns the authenticated username of the current connection.
    ///
    /// - Documentation: [ACL WHOAMI](https:/valkey.io/commands/acl-whoami)
    /// - Available: 6.0.0
    /// - Complexity: O(1)
    /// - Returns: [String]: The username of the current connection.
    @inlinable
    public func aclWhoami() async throws -> ACL.WHOAMI.Response {
        try await send(command: ACL.WHOAMI())
    }

    /// Asynchronously rewrites the append-only file to disk.
    ///
    /// - Documentation: [BGREWRITEAOF](https:/valkey.io/commands/bgrewriteaof)
    /// - Available: 1.0.0
    /// - Complexity: O(1)
    /// - Returns: [String]: A simple string reply indicating that the rewriting started or is about to start ASAP
    @inlinable
    public func bgrewriteaof() async throws -> BGREWRITEAOF.Response {
        try await send(command: BGREWRITEAOF())
    }

    /// Asynchronously saves the database(s) to disk.
    ///
    /// - Documentation: [BGSAVE](https:/valkey.io/commands/bgsave)
    /// - Available: 1.0.0
    /// - History:
    ///     * 3.2.2: Added the `SCHEDULE` option.
    /// - Complexity: O(1)
    @inlinable
    public func bgsave(schedule: Bool = false) async throws -> String {
        try await send(command: BGSAVE(schedule: schedule))
    }

    /// Returns a count of commands.
    ///
    /// - Documentation: [COMMAND COUNT](https:/valkey.io/commands/command-count)
    /// - Available: 2.8.13
    /// - Complexity: O(1)
    /// - Returns: [Integer]: Number of total commands in this server.
    @inlinable
    public func commandCount() async throws -> Int {
        try await send(command: COMMAND.COUNT())
    }

    /// Returns documentary information about one, multiple or all commands.
    ///
    /// - Documentation: [COMMAND DOCS](https:/valkey.io/commands/command-docs)
    /// - Available: 7.0.0
    /// - Complexity: O(N) where N is the number of commands to look up
    /// - Returns: [Map]: A map where each key is a command name, and each value is the documentary information
    @inlinable
    public func commandDocs(commandName: [String] = []) async throws -> RESPToken.Map {
        try await send(command: COMMAND.DOCS(commandName: commandName))
    }

    /// Extracts the key names from an arbitrary command.
    ///
    /// - Documentation: [COMMAND GETKEYS](https:/valkey.io/commands/command-getkeys)
    /// - Available: 2.8.13
    /// - Complexity: O(N) where N is the number of arguments to the command
    /// - Returns: [Array]: List of keys from the given command.
    @inlinable
    public func commandGetkeys<Command: RESPStringRenderable>(command: Command, arg: [String] = []) async throws -> RESPToken.Array {
        try await send(command: COMMAND.GETKEYS(command: command, arg: arg))
    }

    /// Extracts the key names and access flags for an arbitrary command.
    ///
    /// - Documentation: [COMMAND GETKEYSANDFLAGS](https:/valkey.io/commands/command-getkeysandflags)
    /// - Available: 7.0.0
    /// - Complexity: O(N) where N is the number of arguments to the command
    /// - Returns: [Array]: List of keys from the given command and their usage flags.
    @inlinable
    public func commandGetkeysandflags<Command: RESPStringRenderable>(command: Command, arg: [String] = []) async throws -> RESPToken.Array {
        try await send(command: COMMAND.GETKEYSANDFLAGS(command: command, arg: arg))
    }

    /// Returns helpful text about the different subcommands.
    ///
    /// - Documentation: [COMMAND HELP](https:/valkey.io/commands/command-help)
    /// - Available: 5.0.0
    /// - Complexity: O(1)
    /// - Returns: [Array]: Helpful text about subcommands.
    @inlinable
    public func commandHelp() async throws -> RESPToken.Array {
        try await send(command: COMMAND.HELP())
    }

    /// Returns information about one, multiple or all commands.
    ///
    /// - Documentation: [COMMAND INFO](https:/valkey.io/commands/command-info)
    /// - Available: 2.8.13
    /// - History:
    ///     * 7.0.0: Allowed to be called with no argument to get info on all commands.
    /// - Complexity: O(N) where N is the number of commands to look up
    /// - Returns: One of the following
    ///     * [Array]: Command does not exist.
    ///     * [Array]: Command info array output.
    @inlinable
    public func commandInfo(commandName: [String] = []) async throws -> RESPToken.Array {
        try await send(command: COMMAND.INFO(commandName: commandName))
    }

    /// Returns a list of command names.
    ///
    /// - Documentation: [COMMAND LIST](https:/valkey.io/commands/command-list)
    /// - Available: 7.0.0
    /// - Complexity: O(N) where N is the total number of commands
    /// - Returns: [Array]: Command name.
    @inlinable
    public func commandList(filterby: COMMAND.LIST.Filterby? = nil) async throws -> RESPToken.Array {
        try await send(command: COMMAND.LIST(filterby: filterby))
    }

    /// Returns the effective values of configuration parameters.
    ///
    /// - Documentation: [CONFIG GET](https:/valkey.io/commands/config-get)
    /// - Available: 2.0.0
    /// - History:
    ///     * 7.0.0: Added the ability to pass multiple pattern parameters in one call
    /// - Complexity: O(N) when N is the number of configuration parameters provided
    @inlinable
    public func configGet<Parameter: RESPStringRenderable>(parameter: [Parameter]) async throws -> RESPToken.Map {
        try await send(command: CONFIG.GET(parameter: parameter))
    }

    /// Returns helpful text about the different subcommands.
    ///
    /// - Documentation: [CONFIG HELP](https:/valkey.io/commands/config-help)
    /// - Available: 5.0.0
    /// - Complexity: O(1)
    /// - Returns: [Array]: Helpful text about subcommands.
    @inlinable
    public func configHelp() async throws -> RESPToken.Array {
        try await send(command: CONFIG.HELP())
    }

    /// Resets the server's statistics.
    ///
    /// - Documentation: [CONFIG RESETSTAT](https:/valkey.io/commands/config-resetstat)
    /// - Available: 2.0.0
    /// - Complexity: O(1)
    @inlinable
    public func configResetstat() async throws {
        _ = try await send(command: CONFIG.RESETSTAT())
    }

    /// Persists the effective configuration to file.
    ///
    /// - Documentation: [CONFIG REWRITE](https:/valkey.io/commands/config-rewrite)
    /// - Available: 2.8.0
    /// - Complexity: O(1)
    @inlinable
    public func configRewrite() async throws {
        _ = try await send(command: CONFIG.REWRITE())
    }

    /// Sets configuration parameters in-flight.
    ///
    /// - Documentation: [CONFIG SET](https:/valkey.io/commands/config-set)
    /// - Available: 2.0.0
    /// - History:
    ///     * 7.0.0: Added the ability to set multiple parameters in one call.
    /// - Complexity: O(N) when N is the number of configuration parameters provided
    @inlinable
    public func configSet<Parameter: RESPStringRenderable, Value: RESPStringRenderable>(data: [CONFIG.SET<Parameter, Value>.Data]) async throws {
        _ = try await send(command: CONFIG.SET(data: data))
    }

    /// Returns the number of keys in the database.
    ///
    /// - Documentation: [DBSIZE](https:/valkey.io/commands/dbsize)
    /// - Available: 1.0.0
    /// - Complexity: O(1)
    /// - Returns: [Integer]: The number of keys in the currently-selected database.
    @inlinable
    public func dbsize() async throws -> Int {
        try await send(command: DBSIZE())
    }

    /// Starts a coordinated failover from a server to one of its replicas.
    ///
    /// - Documentation: [FAILOVER](https:/valkey.io/commands/failover)
    /// - Available: 6.2.0
    /// - Complexity: O(1)
    @inlinable
    public func failover(target: FAILOVER.Target? = nil, abort: Bool = false, milliseconds: Int? = nil) async throws {
        _ = try await send(command: FAILOVER(target: target, abort: abort, milliseconds: milliseconds))
    }

    /// Removes all keys from all databases.
    ///
    /// - Documentation: [FLUSHALL](https:/valkey.io/commands/flushall)
    /// - Available: 1.0.0
    /// - History:
    ///     * 4.0.0: Added the `ASYNC` flushing mode modifier.
    ///     * 6.2.0: Added the `SYNC` flushing mode modifier.
    /// - Complexity: O(N) where N is the total number of keys in all databases
    @inlinable
    public func flushall(flushType: FLUSHALL.FlushType? = nil) async throws {
        _ = try await send(command: FLUSHALL(flushType: flushType))
    }

    /// Remove all keys from the current database.
    ///
    /// - Documentation: [FLUSHDB](https:/valkey.io/commands/flushdb)
    /// - Available: 1.0.0
    /// - History:
    ///     * 4.0.0: Added the `ASYNC` flushing mode modifier.
    ///     * 6.2.0: Added the `SYNC` flushing mode modifier.
    /// - Complexity: O(N) where N is the number of keys in the selected database
    @inlinable
    public func flushdb(flushType: FLUSHDB.FlushType? = nil) async throws {
        _ = try await send(command: FLUSHDB(flushType: flushType))
    }

    /// Returns information and statistics about the server.
    ///
    /// - Documentation: [INFO](https:/valkey.io/commands/info)
    /// - Available: 1.0.0
    /// - History:
    ///     * 7.0.0: Added support for taking multiple section arguments.
    /// - Complexity: O(1)
    /// - Returns: [String]: A map of info fields, one field per line in the form of <field>:<value> where the value can be a comma separated map like <key>=<val>. Also contains section header lines starting with `#` and blank lines.
    @inlinable
    public func info(section: [String] = []) async throws -> INFO.Response {
        try await send(command: INFO(section: section))
    }

    /// Returns the Unix timestamp of the last successful save to disk.
    ///
    /// - Documentation: [LASTSAVE](https:/valkey.io/commands/lastsave)
    /// - Available: 1.0.0
    /// - Complexity: O(1)
    /// - Returns: [Integer]: UNIX TIME of the last DB save executed with success.
    @inlinable
    public func lastsave() async throws -> Int {
        try await send(command: LASTSAVE())
    }

    /// Returns a human-readable latency analysis report.
    ///
    /// - Documentation: [LATENCY DOCTOR](https:/valkey.io/commands/latency-doctor)
    /// - Available: 2.8.13
    /// - Complexity: O(1)
    /// - Returns: [String]: A human readable latency analysis report.
    @inlinable
    public func latencyDoctor() async throws -> LATENCY.DOCTOR.Response {
        try await send(command: LATENCY.DOCTOR())
    }

    /// Returns a latency graph for an event.
    ///
    /// - Documentation: [LATENCY GRAPH](https:/valkey.io/commands/latency-graph)
    /// - Available: 2.8.13
    /// - Complexity: O(1)
    /// - Returns: [String]: Latency graph
    @inlinable
    public func latencyGraph<Event: RESPStringRenderable>(event: Event) async throws -> LATENCY.GRAPH.Response {
        try await send(command: LATENCY.GRAPH(event: event))
    }

    /// Returns helpful text about the different subcommands.
    ///
    /// - Documentation: [LATENCY HELP](https:/valkey.io/commands/latency-help)
    /// - Available: 2.8.13
    /// - Complexity: O(1)
    /// - Returns: [Array]: Helpful text about subcommands.
    @inlinable
    public func latencyHelp() async throws -> RESPToken.Array {
        try await send(command: LATENCY.HELP())
    }

    /// Returns the cumulative distribution of latencies of a subset or all commands.
    ///
    /// - Documentation: [LATENCY HISTOGRAM](https:/valkey.io/commands/latency-histogram)
    /// - Available: 7.0.0
    /// - Complexity: O(N) where N is the number of commands with latency information being retrieved.
    /// - Returns: [Map]: A map where each key is a command name, and each value is a map with the total calls, and an inner map of the histogram time buckets.
    @inlinable
    public func latencyHistogram(command: [String] = []) async throws -> RESPToken.Map {
        try await send(command: LATENCY.HISTOGRAM(command: command))
    }

    /// Returns timestamp-latency samples for an event.
    ///
    /// - Documentation: [LATENCY HISTORY](https:/valkey.io/commands/latency-history)
    /// - Available: 2.8.13
    /// - Complexity: O(1)
    /// - Returns: [Array]: An array where each element is a two elements array representing the timestamp and the latency of the event.
    @inlinable
    public func latencyHistory<Event: RESPStringRenderable>(event: Event) async throws -> RESPToken.Array {
        try await send(command: LATENCY.HISTORY(event: event))
    }

    /// Returns the latest latency samples for all events.
    ///
    /// - Documentation: [LATENCY LATEST](https:/valkey.io/commands/latency-latest)
    /// - Available: 2.8.13
    /// - Complexity: O(1)
    /// - Returns: [Array]: An array where each element is a four elements array representing the event's name, timestamp, latest and all-time latency measurements.
    @inlinable
    public func latencyLatest() async throws -> RESPToken.Array {
        try await send(command: LATENCY.LATEST())
    }

    /// Resets the latency data for one or more events.
    ///
    /// - Documentation: [LATENCY RESET](https:/valkey.io/commands/latency-reset)
    /// - Available: 2.8.13
    /// - Complexity: O(1)
    /// - Returns: [Integer]: Number of event time series that were reset.
    @inlinable
    public func latencyReset(event: [String] = []) async throws -> Int {
        try await send(command: LATENCY.RESET(event: event))
    }

    /// Displays computer art and the server version
    ///
    /// - Documentation: [LOLWUT](https:/valkey.io/commands/lolwut)
    /// - Available: 5.0.0
    /// - Returns: [String]: String containing the generative computer art, and a text with the server version.
    @inlinable
    public func lolwut(version: Int? = nil) async throws -> LOLWUT.Response {
        try await send(command: LOLWUT(version: version))
    }

    /// Outputs a memory problems report.
    ///
    /// - Documentation: [MEMORY DOCTOR](https:/valkey.io/commands/memory-doctor)
    /// - Available: 4.0.0
    /// - Complexity: O(1)
    /// - Returns: [String]: Memory problems report.
    @inlinable
    public func memoryDoctor() async throws -> MEMORY.DOCTOR.Response {
        try await send(command: MEMORY.DOCTOR())
    }

    /// Returns helpful text about the different subcommands.
    ///
    /// - Documentation: [MEMORY HELP](https:/valkey.io/commands/memory-help)
    /// - Available: 4.0.0
    /// - Complexity: O(1)
    /// - Returns: [Array]: Helpful text about subcommands.
    @inlinable
    public func memoryHelp() async throws -> RESPToken.Array {
        try await send(command: MEMORY.HELP())
    }

    /// Returns the allocator statistics.
    ///
    /// - Documentation: [MEMORY MALLOC-STATS](https:/valkey.io/commands/memory-malloc-stats)
    /// - Available: 4.0.0
    /// - Complexity: Depends on how much memory is allocated, could be slow
    /// - Returns: [String]: The memory allocator's internal statistics report.
    @inlinable
    public func memoryMallocStats() async throws -> MEMORY.MALLOCSTATS.Response {
        try await send(command: MEMORY.MALLOCSTATS())
    }

    /// Asks the allocator to release memory.
    ///
    /// - Documentation: [MEMORY PURGE](https:/valkey.io/commands/memory-purge)
    /// - Available: 4.0.0
    /// - Complexity: Depends on how much memory is allocated, could be slow
    @inlinable
    public func memoryPurge() async throws {
        _ = try await send(command: MEMORY.PURGE())
    }

    /// Returns details about memory usage.
    ///
    /// - Documentation: [MEMORY STATS](https:/valkey.io/commands/memory-stats)
    /// - Available: 4.0.0
    /// - Complexity: O(1)
    /// - Returns: [Map]: Memory usage details.
    @inlinable
    public func memoryStats() async throws -> RESPToken.Map {
        try await send(command: MEMORY.STATS())
    }

    /// Estimates the memory usage of a key.
    ///
    /// - Documentation: [MEMORY USAGE](https:/valkey.io/commands/memory-usage)
    /// - Available: 4.0.0
    /// - Complexity: O(N) where N is the number of samples.
    /// - Returns: One of the following
    ///     * [Integer]: Number of bytes that a key and its value require to be stored in RAM.
    ///     * [Null]: Key does not exist.
    @inlinable
    public func memoryUsage(key: ValkeyKey, count: Int? = nil) async throws -> Int? {
        try await send(command: MEMORY.USAGE(key: key, count: count))
    }

    /// Returns helpful text about the different subcommands.
    ///
    /// - Documentation: [MODULE HELP](https:/valkey.io/commands/module-help)
    /// - Available: 5.0.0
    /// - Complexity: O(1)
    /// - Returns: [Array]: Helpful text about subcommands.
    @inlinable
    public func moduleHelp() async throws -> RESPToken.Array {
        try await send(command: MODULE.HELP())
    }

    /// Returns all loaded modules.
    ///
    /// - Documentation: [MODULE LIST](https:/valkey.io/commands/module-list)
    /// - Available: 4.0.0
    /// - Complexity: O(N) where N is the number of loaded modules.
    /// - Returns: [Array]: Returns information about the modules loaded to the server.
    @inlinable
    public func moduleList() async throws -> RESPToken.Array {
        try await send(command: MODULE.LIST())
    }

    /// Loads a module.
    ///
    /// - Documentation: [MODULE LOAD](https:/valkey.io/commands/module-load)
    /// - Available: 4.0.0
    /// - Complexity: O(1)
    @inlinable
    public func moduleLoad<Path: RESPStringRenderable>(path: Path, arg: [String] = []) async throws {
        _ = try await send(command: MODULE.LOAD(path: path, arg: arg))
    }

    /// Loads a module using extended parameters.
    ///
    /// - Documentation: [MODULE LOADEX](https:/valkey.io/commands/module-loadex)
    /// - Available: 7.0.0
    /// - Complexity: O(1)
    @inlinable
    public func moduleLoadex<Path: RESPStringRenderable>(path: Path, configs: [MODULE.LOADEX<Path>.Configs] = [], args: [String] = []) async throws {
        _ = try await send(command: MODULE.LOADEX(path: path, configs: configs, args: args))
    }

    /// Unloads a module.
    ///
    /// - Documentation: [MODULE UNLOAD](https:/valkey.io/commands/module-unload)
    /// - Available: 4.0.0
    /// - Complexity: O(1)
    @inlinable
    public func moduleUnload<Name: RESPStringRenderable>(name: Name) async throws {
        _ = try await send(command: MODULE.UNLOAD(name: name))
    }

    /// An internal command for configuring the replication stream.
    ///
    /// - Documentation: [REPLCONF](https:/valkey.io/commands/replconf)
    /// - Available: 3.0.0
    /// - Complexity: O(1)
    @inlinable
    public func replconf() async throws {
        _ = try await send(command: REPLCONF())
    }

    /// Configures a server as replica of another, or promotes it to a primary.
    ///
    /// - Documentation: [REPLICAOF](https:/valkey.io/commands/replicaof)
    /// - Available: 5.0.0
    /// - Complexity: O(1)
    /// - Returns: [String]: ReplicaOf status.
    @inlinable
    public func replicaof(args: REPLICAOF.Args) async throws -> REPLICAOF.Response {
        try await send(command: REPLICAOF(args: args))
    }

    /// An internal command for migrating keys in a cluster.
    ///
    /// - Documentation: [RESTORE-ASKING](https:/valkey.io/commands/restore-asking)
    /// - Available: 3.0.0
    /// - History:
    ///     * 3.0.0: Added the `REPLACE` modifier.
    ///     * 5.0.0: Added the `ABSTTL` modifier.
    ///     * 5.0.0: Added the `IDLETIME` and `FREQ` options.
    /// - Complexity: O(1) to create the new key and additional O(N*M) to reconstruct the serialized value, where N is the number of objects composing the value and M their average size. For small string values the time complexity is thus O(1)+O(1*M) where M is small, so simply O(1). However for sorted set values the complexity is O(N*M*log(N)) because inserting values into sorted sets is O(log(N)).
    @inlinable
    public func restoreAsking<SerializedValue: RESPStringRenderable>(key: ValkeyKey, ttl: Int, serializedValue: SerializedValue, replace: Bool = false, absttl: Bool = false, seconds: Int? = nil, frequency: Int? = nil) async throws {
        _ = try await send(command: RESTOREASKING(key: key, ttl: ttl, serializedValue: serializedValue, replace: replace, absttl: absttl, seconds: seconds, frequency: frequency))
    }

    /// Returns the replication role.
    ///
    /// - Documentation: [ROLE](https:/valkey.io/commands/role)
    /// - Available: 2.8.12
    /// - Complexity: O(1)
    @inlinable
    public func role() async throws -> RESPToken.Array {
        try await send(command: ROLE())
    }

    /// Synchronously saves the database(s) to disk.
    ///
    /// - Documentation: [SAVE](https:/valkey.io/commands/save)
    /// - Available: 1.0.0
    /// - Complexity: O(N) where N is the total number of keys in all databases
    @inlinable
    public func save() async throws {
        _ = try await send(command: SAVE())
    }

    /// Synchronously saves the database(s) to disk and shuts down the server.
    ///
    /// - Documentation: [SHUTDOWN](https:/valkey.io/commands/shutdown)
    /// - Available: 1.0.0
    /// - History:
    ///     * 7.0.0: Added the `NOW`, `FORCE` and `ABORT` modifiers.
    /// - Complexity: O(N) when saving, where N is the total number of keys in all databases when saving data, otherwise O(1)
    /// - Returns: "OK": OK if ABORT was specified and shutdown was aborted. On successful shutdown, nothing is returned since the server quits and the connection is closed. On failure, an error is returned.
    @inlinable
    public func shutdown(abortSelector: SHUTDOWN.AbortSelector? = nil) async throws {
        _ = try await send(command: SHUTDOWN(abortSelector: abortSelector))
    }

    /// Sets a server as a replica of another, or promotes it to being a primary.
    ///
    /// - Documentation: [SLAVEOF](https:/valkey.io/commands/slaveof)
    /// - Available: 1.0.0
    /// - Complexity: O(1)
    /// - Returns: [String]: SlaveOf status.
    @inlinable
    @available(*, deprecated, message: "Since 5.0.0. Replaced by `REPLICAOF`.")
    public func slaveof(args: SLAVEOF.Args) async throws -> SLAVEOF.Response {
        try await send(command: SLAVEOF(args: args))
    }

    /// Returns the slow log's entries.
    ///
    /// - Documentation: [SLOWLOG GET](https:/valkey.io/commands/slowlog-get)
    /// - Available: 2.2.12
    /// - History:
    ///     * 4.0.0: Added client IP address, port and name to the reply.
    /// - Complexity: O(N) where N is the number of entries returned
    /// - Returns: [Array]: Entries from the slow log in chronological order.
    @inlinable
    public func slowlogGet(count: Int? = nil) async throws -> RESPToken.Array {
        try await send(command: SLOWLOG.GET(count: count))
    }

    /// Show helpful text about the different subcommands
    ///
    /// - Documentation: [SLOWLOG HELP](https:/valkey.io/commands/slowlog-help)
    /// - Available: 6.2.0
    /// - Complexity: O(1)
    /// - Returns: [Array]: Helpful text about subcommands.
    @inlinable
    public func slowlogHelp() async throws -> RESPToken.Array {
        try await send(command: SLOWLOG.HELP())
    }

    /// Returns the number of entries in the slow log.
    ///
    /// - Documentation: [SLOWLOG LEN](https:/valkey.io/commands/slowlog-len)
    /// - Available: 2.2.12
    /// - Complexity: O(1)
    /// - Returns: [Integer]: Number of entries in the slow log.
    @inlinable
    public func slowlogLen() async throws -> Int {
        try await send(command: SLOWLOG.LEN())
    }

    /// Clears all entries from the slow log.
    ///
    /// - Documentation: [SLOWLOG RESET](https:/valkey.io/commands/slowlog-reset)
    /// - Available: 2.2.12
    /// - Complexity: O(N) where N is the number of entries in the slowlog
    @inlinable
    public func slowlogReset() async throws {
        _ = try await send(command: SLOWLOG.RESET())
    }

    /// Swaps two databases.
    ///
    /// - Documentation: [SWAPDB](https:/valkey.io/commands/swapdb)
    /// - Available: 4.0.0
    /// - Complexity: O(N) where N is the count of clients watching or blocking on keys from both databases.
    @inlinable
    public func swapdb(index1: Int, index2: Int) async throws {
        _ = try await send(command: SWAPDB(index1: index1, index2: index2))
    }

    /// Returns the server time.
    ///
    /// - Documentation: [TIME](https:/valkey.io/commands/time)
    /// - Available: 2.6.0
    /// - Complexity: O(1)
    /// - Returns: [Array]: Array containing two elements: Unix time in seconds and microseconds.
    @inlinable
    public func time() async throws -> RESPToken.Array {
        try await send(command: TIME())
    }

}
