//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-valkey open source project
//
// Copyright (c) 2025 Apple Inc. and the swift-valkey project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of swift-valkey project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// This file is autogenerated by ValkeyCommandsBuilder

import NIOCore

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

/// Discards a transaction.
public struct DISCARD: ValkeyCommand {
    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("DISCARD")
    }
}

/// Executes all commands in a transaction.
public struct EXEC: ValkeyCommand {
    public typealias Response = RESPToken.Array?

    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("EXEC")
    }
}

/// Starts a transaction.
public struct MULTI: ValkeyCommand {
    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("MULTI")
    }
}

/// Forgets about watched keys of a transaction.
public struct UNWATCH: ValkeyCommand {
    @inlinable public init() {
    }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("UNWATCH")
    }
}

/// Monitors changes to keys to determine the execution of a transaction.
public struct WATCH: ValkeyCommand {
    public var key: [ValkeyKey]

    @inlinable public init(key: [ValkeyKey]) {
        self.key = key
    }

    public var keysAffected: [ValkeyKey] { key }

    @inlinable public func encode(into commandEncoder: inout ValkeyCommandEncoder) {
        commandEncoder.encodeArray("WATCH", key)
    }
}

extension ValkeyConnection {
    /// Discards a transaction.
    ///
    /// - Documentation: [DISCARD](https:/valkey.io/commands/discard)
    /// - Version: 2.0.0
    /// - Complexity: O(N), when N is the number of queued commands
    /// - Categories: TRANSACTION
    /// - Returns: [Simple string](https:/valkey.io/topics/protocol/#simple-strings): `OK`.
    @inlinable
    public func discard() async throws {
        _ = try await send(command: DISCARD())
    }

    /// Executes all commands in a transaction.
    ///
    /// - Documentation: [EXEC](https:/valkey.io/commands/exec)
    /// - Version: 1.2.0
    /// - Complexity: Depends on commands in the transaction
    /// - Categories: TRANSACTION
    /// - Returns: One of the following:
    ///     * [Array](https:/valkey.io/topics/protocol/#arrays): each element being the reply to each of the commands in the atomic transaction.
    ///     * [Null](https:/valkey.io/topics/protocol/#nulls): the transaction was aborted because a `WATCH`ed key was touched.
    @inlinable
    public func exec() async throws -> RESPToken.Array? {
        try await send(command: EXEC())
    }

    /// Starts a transaction.
    ///
    /// - Documentation: [MULTI](https:/valkey.io/commands/multi)
    /// - Version: 1.2.0
    /// - Complexity: O(1)
    /// - Categories: TRANSACTION
    /// - Returns: [Simple string](https:/valkey.io/topics/protocol/#simple-strings): `OK`.
    @inlinable
    public func multi() async throws {
        _ = try await send(command: MULTI())
    }

    /// Forgets about watched keys of a transaction.
    ///
    /// - Documentation: [UNWATCH](https:/valkey.io/commands/unwatch)
    /// - Version: 2.2.0
    /// - Complexity: O(1)
    /// - Categories: TRANSACTION
    /// - Returns: [Simple string](https:/valkey.io/topics/protocol/#simple-strings): `OK`.
    @inlinable
    public func unwatch() async throws {
        _ = try await send(command: UNWATCH())
    }

    /// Monitors changes to keys to determine the execution of a transaction.
    ///
    /// - Documentation: [WATCH](https:/valkey.io/commands/watch)
    /// - Version: 2.2.0
    /// - Complexity: O(1) for every key.
    /// - Categories: TRANSACTION
    /// - Returns: [Simple string](https:/valkey.io/topics/protocol/#simple-strings): `OK`.
    @inlinable
    public func watch(key: [ValkeyKey]) async throws {
        _ = try await send(command: WATCH(key: key))
    }

}
