//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-redis open source project
//
// Copyright (c) 2025 Apple Inc. and the swift-redis project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of swift-redis project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// This file is autogenerated by RedisCommandsBuilder

import NIOCore
import Redis

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

/// A container for function commands.
public enum FUNCTION {
    /// Deletes a library and its functions.
    public struct DELETE: RedisCommand {
        public typealias Response = RESPToken

        public var libraryName: String

        @inlinable public init(libraryName: String) {
            self.libraryName = libraryName
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("FUNCTION", "DELETE", libraryName)
        }
    }

    /// Dumps all libraries into a serialized binary payload.
    public struct DUMP: RedisCommand {
        public typealias Response = String


        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("FUNCTION", "DUMP")
        }
    }

    /// Deletes all libraries and functions.
    public struct FLUSH: RedisCommand {
        public enum FlushType: RESPRenderable {
            case async
            case sync

            @inlinable
            public func encode(into commandEncoder: inout RedisCommandEncoder) -> Int {
                switch self {
                case .async: "ASYNC".encode(into: &commandEncoder)
                case .sync: "SYNC".encode(into: &commandEncoder)
                }
            }
        }
        public typealias Response = RESPToken

        public var flushType: FlushType? = nil

        @inlinable public init(flushType: FlushType? = nil) {
            self.flushType = flushType
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("FUNCTION", "FLUSH", flushType)
        }
    }

    /// Returns helpful text about the different subcommands.
    public struct HELP: RedisCommand {
        public typealias Response = [RESPToken]


        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("FUNCTION", "HELP")
        }
    }

    /// Terminates a function during execution.
    public struct KILL: RedisCommand {
        public typealias Response = RESPToken


        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("FUNCTION", "KILL")
        }
    }

    /// Returns information about all libraries.
    public struct LIST: RedisCommand {
        public typealias Response = [RESPToken]

        public var libraryNamePattern: String? = nil
        public var withcode: Bool = false

        @inlinable public init(libraryNamePattern: String? = nil, withcode: Bool = false) {
            self.libraryNamePattern = libraryNamePattern
            self.withcode = withcode
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("FUNCTION", "LIST", RESPWithToken("LIBRARYNAME", libraryNamePattern), RedisPureToken("WITHCODE", withcode))
        }
    }

    /// Creates a library.
    public struct LOAD: RedisCommand {
        public typealias Response = String

        public var replace: Bool = false
        public var functionCode: String

        @inlinable public init(replace: Bool = false, functionCode: String) {
            self.replace = replace
            self.functionCode = functionCode
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("FUNCTION", "LOAD", RedisPureToken("REPLACE", replace), functionCode)
        }
    }

    /// Restores all libraries from a payload.
    public struct RESTORE: RedisCommand {
        public enum Policy: RESPRenderable {
            case flush
            case append
            case replace

            @inlinable
            public func encode(into commandEncoder: inout RedisCommandEncoder) -> Int {
                switch self {
                case .flush: "FLUSH".encode(into: &commandEncoder)
                case .append: "APPEND".encode(into: &commandEncoder)
                case .replace: "REPLACE".encode(into: &commandEncoder)
                }
            }
        }
        public typealias Response = RESPToken

        public var serializedValue: String
        public var policy: Policy? = nil

        @inlinable public init(serializedValue: String, policy: Policy? = nil) {
            self.serializedValue = serializedValue
            self.policy = policy
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("FUNCTION", "RESTORE", serializedValue, policy)
        }
    }

    /// Returns information about a function during execution.
    public struct STATS: RedisCommand {
        public typealias Response = [String: RESPToken]


        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("FUNCTION", "STATS")
        }
    }

}

/// A container for Lua scripts management commands.
public enum SCRIPT {
    /// Sets the debug mode of server-side Lua scripts.
    public struct DEBUG: RedisCommand {
        public enum Mode: RESPRenderable {
            case yes
            case sync
            case no

            @inlinable
            public func encode(into commandEncoder: inout RedisCommandEncoder) -> Int {
                switch self {
                case .yes: "YES".encode(into: &commandEncoder)
                case .sync: "SYNC".encode(into: &commandEncoder)
                case .no: "NO".encode(into: &commandEncoder)
                }
            }
        }
        public typealias Response = RESPToken

        public var mode: Mode

        @inlinable public init(mode: Mode) {
            self.mode = mode
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("SCRIPT", "DEBUG", mode)
        }
    }

    /// Determines whether server-side Lua scripts exist in the script cache.
    public struct EXISTS: RedisCommand {
        public typealias Response = [RESPToken]

        public var sha1: [String]

        @inlinable public init(sha1: [String]) {
            self.sha1 = sha1
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("SCRIPT", "EXISTS", sha1)
        }
    }

    /// Removes all server-side Lua scripts from the script cache.
    public struct FLUSH: RedisCommand {
        public enum FlushType: RESPRenderable {
            case async
            case sync

            @inlinable
            public func encode(into commandEncoder: inout RedisCommandEncoder) -> Int {
                switch self {
                case .async: "ASYNC".encode(into: &commandEncoder)
                case .sync: "SYNC".encode(into: &commandEncoder)
                }
            }
        }
        public typealias Response = RESPToken

        public var flushType: FlushType? = nil

        @inlinable public init(flushType: FlushType? = nil) {
            self.flushType = flushType
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("SCRIPT", "FLUSH", flushType)
        }
    }

    /// Returns helpful text about the different subcommands.
    public struct HELP: RedisCommand {
        public typealias Response = [RESPToken]


        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("SCRIPT", "HELP")
        }
    }

    /// Terminates a server-side Lua script during execution.
    public struct KILL: RedisCommand {
        public typealias Response = RESPToken


        @inlinable public init() {
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("SCRIPT", "KILL")
        }
    }

    /// Loads a server-side Lua script to the script cache.
    public struct LOAD: RedisCommand {
        public typealias Response = String

        public var script: String

        @inlinable public init(script: String) {
            self.script = script
        }

        @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
            commandEncoder.encodeArray("SCRIPT", "LOAD", script)
        }
    }

}

/// Executes a server-side Lua script.
public struct EVAL: RedisCommand {
    public typealias Response = RESPToken

    public var script: String
    public var key: [RedisKey] = []
    public var arg: [String] = []

    @inlinable public init(script: String, key: [RedisKey] = [], arg: [String] = []) {
        self.script = script
        self.key = key
        self.arg = arg
    }

    @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
        commandEncoder.encodeArray("EVAL", script, RESPArrayWithCount(key), arg)
    }
}

/// Executes a server-side Lua script by SHA1 digest.
public struct EVALSHA: RedisCommand {
    public typealias Response = RESPToken

    public var sha1: String
    public var key: [RedisKey] = []
    public var arg: [String] = []

    @inlinable public init(sha1: String, key: [RedisKey] = [], arg: [String] = []) {
        self.sha1 = sha1
        self.key = key
        self.arg = arg
    }

    @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
        commandEncoder.encodeArray("EVALSHA", sha1, RESPArrayWithCount(key), arg)
    }
}

/// Executes a read-only server-side Lua script by SHA1 digest.
public struct EVALSHARO: RedisCommand {
    public typealias Response = RESPToken

    public var sha1: String
    public var key: [RedisKey] = []
    public var arg: [String] = []

    @inlinable public init(sha1: String, key: [RedisKey] = [], arg: [String] = []) {
        self.sha1 = sha1
        self.key = key
        self.arg = arg
    }

    @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
        commandEncoder.encodeArray("EVALSHA_RO", sha1, RESPArrayWithCount(key), arg)
    }
}

/// Executes a read-only server-side Lua script.
public struct EVALRO: RedisCommand {
    public typealias Response = RESPToken

    public var script: String
    public var key: [RedisKey] = []
    public var arg: [String] = []

    @inlinable public init(script: String, key: [RedisKey] = [], arg: [String] = []) {
        self.script = script
        self.key = key
        self.arg = arg
    }

    @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
        commandEncoder.encodeArray("EVAL_RO", script, RESPArrayWithCount(key), arg)
    }
}

/// Invokes a function.
public struct FCALL: RedisCommand {
    public typealias Response = RESPToken

    public var function: String
    public var key: [RedisKey] = []
    public var arg: [String] = []

    @inlinable public init(function: String, key: [RedisKey] = [], arg: [String] = []) {
        self.function = function
        self.key = key
        self.arg = arg
    }

    @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
        commandEncoder.encodeArray("FCALL", function, RESPArrayWithCount(key), arg)
    }
}

/// Invokes a read-only function.
public struct FCALLRO: RedisCommand {
    public typealias Response = RESPToken

    public var function: String
    public var key: [RedisKey] = []
    public var arg: [String] = []

    @inlinable public init(function: String, key: [RedisKey] = [], arg: [String] = []) {
        self.function = function
        self.key = key
        self.arg = arg
    }

    @inlinable public func encode(into commandEncoder: inout RedisCommandEncoder) {
        commandEncoder.encodeArray("FCALL_RO", function, RESPArrayWithCount(key), arg)
    }
}


extension RedisConnection {
    /// Executes a server-side Lua script.
    ///
    /// - Documentation: [EVAL](https:/redis.io/docs/latest/commands/eval)
    /// - Version: 2.6.0
    /// - Complexity: Depends on the script that is executed.
    /// - Categories: @slow, @scripting
    /// - Returns: The return value depends on the script that was executed.
    @inlinable
    public func eval(script: String, key: [RedisKey] = [], arg: [String] = []) async throws -> RESPToken {
        try await send(command: EVAL(script: script, key: key, arg: arg))
    }

    /// Executes a server-side Lua script by SHA1 digest.
    ///
    /// - Documentation: [EVALSHA](https:/redis.io/docs/latest/commands/evalsha)
    /// - Version: 2.6.0
    /// - Complexity: Depends on the script that is executed.
    /// - Categories: @slow, @scripting
    /// - Returns: The return value depends on the script that was executed.
    @inlinable
    public func evalsha(sha1: String, key: [RedisKey] = [], arg: [String] = []) async throws -> RESPToken {
        try await send(command: EVALSHA(sha1: sha1, key: key, arg: arg))
    }

    /// Executes a read-only server-side Lua script by SHA1 digest.
    ///
    /// - Documentation: [EVALSHA_RO](https:/redis.io/docs/latest/commands/evalsha_ro)
    /// - Version: 7.0.0
    /// - Complexity: Depends on the script that is executed.
    /// - Categories: @slow, @scripting
    /// - Returns: The return value depends on the script that was executed.
    @inlinable
    public func evalshaRo(sha1: String, key: [RedisKey] = [], arg: [String] = []) async throws -> RESPToken {
        try await send(command: EVALSHARO(sha1: sha1, key: key, arg: arg))
    }

    /// Executes a read-only server-side Lua script.
    ///
    /// - Documentation: [EVAL_RO](https:/redis.io/docs/latest/commands/eval_ro)
    /// - Version: 7.0.0
    /// - Complexity: Depends on the script that is executed.
    /// - Categories: @slow, @scripting
    /// - Returns: The return value depends on the script that was executed.
    @inlinable
    public func evalRo(script: String, key: [RedisKey] = [], arg: [String] = []) async throws -> RESPToken {
        try await send(command: EVALRO(script: script, key: key, arg: arg))
    }

    /// Invokes a function.
    ///
    /// - Documentation: [FCALL](https:/redis.io/docs/latest/commands/fcall)
    /// - Version: 7.0.0
    /// - Complexity: Depends on the function that is executed.
    /// - Categories: @slow, @scripting
    /// - Returns: The return value depends on the function that was executed.
    @inlinable
    public func fcall(function: String, key: [RedisKey] = [], arg: [String] = []) async throws -> RESPToken {
        try await send(command: FCALL(function: function, key: key, arg: arg))
    }

    /// Invokes a read-only function.
    ///
    /// - Documentation: [FCALL_RO](https:/redis.io/docs/latest/commands/fcall_ro)
    /// - Version: 7.0.0
    /// - Complexity: Depends on the function that is executed.
    /// - Categories: @slow, @scripting
    /// - Returns: The return value depends on the function that was executed.
    @inlinable
    public func fcallRo(function: String, key: [RedisKey] = [], arg: [String] = []) async throws -> RESPToken {
        try await send(command: FCALLRO(function: function, key: key, arg: arg))
    }

    /// Deletes a library and its functions.
    ///
    /// - Documentation: [FUNCTION DELETE](https:/redis.io/docs/latest/commands/function-delete)
    /// - Version: 7.0.0
    /// - Complexity: O(1)
    /// - Categories: @write, @slow, @scripting
    /// - Returns: [Simple string](https:/redis.io/docs/reference/protocol-spec#simple-strings): `OK`.
    @inlinable
    public func functionDelete(libraryName: String) async throws -> RESPToken {
        try await send(command: FUNCTION.DELETE(libraryName: libraryName))
    }

    /// Dumps all libraries into a serialized binary payload.
    ///
    /// - Documentation: [FUNCTION DUMP](https:/redis.io/docs/latest/commands/function-dump)
    /// - Version: 7.0.0
    /// - Complexity: O(N) where N is the number of functions
    /// - Categories: @slow, @scripting
    /// - Returns: [Bulk string](https:/redis.io/docs/reference/protocol-spec#bulk-strings): the serialized payload
    @inlinable
    public func functionDump() async throws -> String {
        try await send(command: FUNCTION.DUMP())
    }

    /// Deletes all libraries and functions.
    ///
    /// - Documentation: [FUNCTION FLUSH](https:/redis.io/docs/latest/commands/function-flush)
    /// - Version: 7.0.0
    /// - Complexity: O(N) where N is the number of functions deleted
    /// - Categories: @write, @slow, @scripting
    /// - Returns: [Simple string](https:/redis.io/docs/reference/protocol-spec#simple-strings): `OK`.
    @inlinable
    public func functionFlush(flushType: FUNCTION.FLUSH.FlushType? = nil) async throws -> RESPToken {
        try await send(command: FUNCTION.FLUSH(flushType: flushType))
    }

    /// Returns helpful text about the different subcommands.
    ///
    /// - Documentation: [FUNCTION HELP](https:/redis.io/docs/latest/commands/function-help)
    /// - Version: 7.0.0
    /// - Complexity: O(1)
    /// - Categories: @slow, @scripting
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list of sub-commands and their descriptions.
    @inlinable
    public func functionHelp() async throws -> [RESPToken] {
        try await send(command: FUNCTION.HELP())
    }

    /// Terminates a function during execution.
    ///
    /// - Documentation: [FUNCTION KILL](https:/redis.io/docs/latest/commands/function-kill)
    /// - Version: 7.0.0
    /// - Complexity: O(1)
    /// - Categories: @slow, @scripting
    /// - Returns: [Simple string](https:/redis.io/docs/reference/protocol-spec#simple-strings): `OK`.
    @inlinable
    public func functionKill() async throws -> RESPToken {
        try await send(command: FUNCTION.KILL())
    }

    /// Returns information about all libraries.
    ///
    /// - Documentation: [FUNCTION LIST](https:/redis.io/docs/latest/commands/function-list)
    /// - Version: 7.0.0
    /// - Complexity: O(N) where N is the number of functions
    /// - Categories: @slow, @scripting
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): information about functions and libraries.
    @inlinable
    public func functionList(libraryNamePattern: String? = nil, withcode: Bool = false) async throws -> [RESPToken] {
        try await send(command: FUNCTION.LIST(libraryNamePattern: libraryNamePattern, withcode: withcode))
    }

    /// Creates a library.
    ///
    /// - Documentation: [FUNCTION LOAD](https:/redis.io/docs/latest/commands/function-load)
    /// - Version: 7.0.0
    /// - Complexity: O(1) (considering compilation time is redundant)
    /// - Categories: @write, @slow, @scripting
    /// - Returns: [Bulk string](https:/redis.io/docs/reference/protocol-spec#bulk-strings): the library name that was loaded.
    @inlinable
    public func functionLoad(replace: Bool = false, functionCode: String) async throws -> String {
        try await send(command: FUNCTION.LOAD(replace: replace, functionCode: functionCode))
    }

    /// Restores all libraries from a payload.
    ///
    /// - Documentation: [FUNCTION RESTORE](https:/redis.io/docs/latest/commands/function-restore)
    /// - Version: 7.0.0
    /// - Complexity: O(N) where N is the number of functions on the payload
    /// - Categories: @write, @slow, @scripting
    /// - Returns: [Simple string](https:/redis.io/docs/reference/protocol-spec#simple-strings): `OK`.
    @inlinable
    public func functionRestore(serializedValue: String, policy: FUNCTION.RESTORE.Policy? = nil) async throws -> RESPToken {
        try await send(command: FUNCTION.RESTORE(serializedValue: serializedValue, policy: policy))
    }

    /// Returns information about a function during execution.
    ///
    /// - Documentation: [FUNCTION STATS](https:/redis.io/docs/latest/commands/function-stats)
    /// - Version: 7.0.0
    /// - Complexity: O(1)
    /// - Categories: @slow, @scripting
    /// - Returns: [Map](https:/redis.io/docs/reference/protocol-spec#maps): information about the function that's currently running and information about the available execution engines.
    @inlinable
    public func functionStats() async throws -> [String: RESPToken] {
        try await send(command: FUNCTION.STATS())
    }

    /// Sets the debug mode of server-side Lua scripts.
    ///
    /// - Documentation: [SCRIPT DEBUG](https:/redis.io/docs/latest/commands/script-debug)
    /// - Version: 3.2.0
    /// - Complexity: O(1)
    /// - Categories: @slow, @scripting
    /// - Returns: [Simple string](https:/redis.io/docs/reference/protocol-spec#simple-strings): `OK`.
    @inlinable
    public func scriptDebug(mode: SCRIPT.DEBUG.Mode) async throws -> RESPToken {
        try await send(command: SCRIPT.DEBUG(mode: mode))
    }

    /// Determines whether server-side Lua scripts exist in the script cache.
    ///
    /// - Documentation: [SCRIPT EXISTS](https:/redis.io/docs/latest/commands/script-exists)
    /// - Version: 2.6.0
    /// - Complexity: O(N) with N being the number of scripts to check (so checking a single script is an O(1) operation).
    /// - Categories: @slow, @scripting
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): an array of integers that correspond to the specified SHA1 digest arguments.
    @inlinable
    public func scriptExists(sha1: [String]) async throws -> [RESPToken] {
        try await send(command: SCRIPT.EXISTS(sha1: sha1))
    }

    /// Removes all server-side Lua scripts from the script cache.
    ///
    /// - Documentation: [SCRIPT FLUSH](https:/redis.io/docs/latest/commands/script-flush)
    /// - Version: 2.6.0
    /// - Complexity: O(N) with N being the number of scripts in cache
    /// - Categories: @slow, @scripting
    /// - Returns: [Simple string](https:/redis.io/docs/reference/protocol-spec#simple-strings): `OK`.
    @inlinable
    public func scriptFlush(flushType: SCRIPT.FLUSH.FlushType? = nil) async throws -> RESPToken {
        try await send(command: SCRIPT.FLUSH(flushType: flushType))
    }

    /// Returns helpful text about the different subcommands.
    ///
    /// - Documentation: [SCRIPT HELP](https:/redis.io/docs/latest/commands/script-help)
    /// - Version: 5.0.0
    /// - Complexity: O(1)
    /// - Categories: @slow, @scripting
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list of sub-commands and their descriptions.
    @inlinable
    public func scriptHelp() async throws -> [RESPToken] {
        try await send(command: SCRIPT.HELP())
    }

    /// Terminates a server-side Lua script during execution.
    ///
    /// - Documentation: [SCRIPT KILL](https:/redis.io/docs/latest/commands/script-kill)
    /// - Version: 2.6.0
    /// - Complexity: O(1)
    /// - Categories: @slow, @scripting
    /// - Returns: [Simple string](https:/redis.io/docs/reference/protocol-spec#simple-strings): `OK`.
    @inlinable
    public func scriptKill() async throws -> RESPToken {
        try await send(command: SCRIPT.KILL())
    }

    /// Loads a server-side Lua script to the script cache.
    ///
    /// - Documentation: [SCRIPT LOAD](https:/redis.io/docs/latest/commands/script-load)
    /// - Version: 2.6.0
    /// - Complexity: O(N) with N being the length in bytes of the script body.
    /// - Categories: @slow, @scripting
    /// - Returns: [Bulk string](https:/redis.io/docs/reference/protocol-spec#bulk-strings): the SHA1 digest of the script added into the script cache.
    @inlinable
    public func scriptLoad(script: String) async throws -> String {
        try await send(command: SCRIPT.LOAD(script: script))
    }

}
