//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-redis open source project
//
// Copyright (c) 2025 Apple Inc. and the swift-redis project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of swift-redis project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// This file is autogenerated by RedisCommandsBuilder

import NIOCore
import Redis

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension RESPCommand {
    /// Adds one or more members to a set. Creates the key if it doesn't exist.
    ///
    /// - Documentation: [SADD](https:/redis.io/docs/latest/commands/sadd)
    /// - Version: 1.0.0
    /// - Complexity: O(1) for each element added, so O(N) to add N elements when the command is called with multiple arguments.
    /// - Categories: @write, @set, @fast
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of elements that were added to the set, not including all the elements already present in the set.
    @inlinable
    public static func sadd(key: RedisKey, member: String) -> RESPCommand {
        RESPCommand("SADD", key, member)
    }

    /// Adds one or more members to a set. Creates the key if it doesn't exist.
    ///
    /// - Documentation: [SADD](https:/redis.io/docs/latest/commands/sadd)
    /// - Version: 1.0.0
    /// - Complexity: O(1) for each element added, so O(N) to add N elements when the command is called with multiple arguments.
    /// - Categories: @write, @set, @fast
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of elements that were added to the set, not including all the elements already present in the set.
    @inlinable
    public static func sadd(key: RedisKey, members: [String]) -> RESPCommand {
        RESPCommand("SADD", key, members)
    }

    /// Returns the number of members in a set.
    ///
    /// - Documentation: [SCARD](https:/redis.io/docs/latest/commands/scard)
    /// - Version: 1.0.0
    /// - Complexity: O(1)
    /// - Categories: @read, @set, @fast
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): The cardinality (number of elements) of the set, or 0 if the key does not exist.
    @inlinable
    public static func scard(key: RedisKey) -> RESPCommand {
        RESPCommand("SCARD", key)
    }

    /// Returns the difference of multiple sets.
    ///
    /// - Documentation: [SDIFF](https:/redis.io/docs/latest/commands/sdiff)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @read, @set, @slow
    /// - Response: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public static func sdiff(key: RedisKey) -> RESPCommand {
        RESPCommand("SDIFF", key)
    }

    /// Returns the difference of multiple sets.
    ///
    /// - Documentation: [SDIFF](https:/redis.io/docs/latest/commands/sdiff)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @read, @set, @slow
    /// - Response: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public static func sdiff(keys: [RedisKey]) -> RESPCommand {
        RESPCommand("SDIFF", keys)
    }

    /// Stores the difference of multiple sets in a key.
    ///
    /// - Documentation: [SDIFFSTORE](https:/redis.io/docs/latest/commands/sdiffstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @write, @set, @slow
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of elements in the resulting set.
    @inlinable
    public static func sdiffstore(destination: RedisKey, key: RedisKey) -> RESPCommand {
        RESPCommand("SDIFFSTORE", destination, key)
    }

    /// Stores the difference of multiple sets in a key.
    ///
    /// - Documentation: [SDIFFSTORE](https:/redis.io/docs/latest/commands/sdiffstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @write, @set, @slow
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of elements in the resulting set.
    @inlinable
    public static func sdiffstore(destination: RedisKey, keys: [RedisKey]) -> RESPCommand {
        RESPCommand("SDIFFSTORE", destination, keys)
    }

    /// Returns the intersect of multiple sets.
    ///
    /// - Documentation: [SINTER](https:/redis.io/docs/latest/commands/sinter)
    /// - Version: 1.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @read, @set, @slow
    /// - Response: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public static func sinter(key: RedisKey) -> RESPCommand {
        RESPCommand("SINTER", key)
    }

    /// Returns the intersect of multiple sets.
    ///
    /// - Documentation: [SINTER](https:/redis.io/docs/latest/commands/sinter)
    /// - Version: 1.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @read, @set, @slow
    /// - Response: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public static func sinter(keys: [RedisKey]) -> RESPCommand {
        RESPCommand("SINTER", keys)
    }

    /// Returns the number of members of the intersect of multiple sets.
    ///
    /// - Documentation: [SINTERCARD](https:/redis.io/docs/latest/commands/sintercard)
    /// - Version: 7.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @read, @set, @slow
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of the elements in the resulting intersection.
    @inlinable
    public static func sintercard(key: RedisKey, limit: Int? = nil) -> RESPCommand {
        RESPCommand("SINTERCARD", 1, key, RESPWithToken("LIMIT", limit))
    }

    /// Returns the number of members of the intersect of multiple sets.
    ///
    /// - Documentation: [SINTERCARD](https:/redis.io/docs/latest/commands/sintercard)
    /// - Version: 7.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @read, @set, @slow
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of the elements in the resulting intersection.
    @inlinable
    public static func sintercard(keys: [RedisKey], limit: Int? = nil) -> RESPCommand {
        RESPCommand("SINTERCARD", RESPArrayWithCount(keys), RESPWithToken("LIMIT", limit))
    }

    /// Stores the intersect of multiple sets in a key.
    ///
    /// - Documentation: [SINTERSTORE](https:/redis.io/docs/latest/commands/sinterstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @write, @set, @slow
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of the elements in the result set.
    @inlinable
    public static func sinterstore(destination: RedisKey, key: RedisKey) -> RESPCommand {
        RESPCommand("SINTERSTORE", destination, key)
    }

    /// Stores the intersect of multiple sets in a key.
    ///
    /// - Documentation: [SINTERSTORE](https:/redis.io/docs/latest/commands/sinterstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @write, @set, @slow
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of the elements in the result set.
    @inlinable
    public static func sinterstore(destination: RedisKey, keys: [RedisKey]) -> RESPCommand {
        RESPCommand("SINTERSTORE", destination, keys)
    }

    /// Determines whether a member belongs to a set.
    ///
    /// - Documentation: [SISMEMBER](https:/redis.io/docs/latest/commands/sismember)
    /// - Version: 1.0.0
    /// - Complexity: O(1)
    /// - Categories: @read, @set, @fast
    /// - Response: One of the following:
    ///     * [Integer](https:/redis.io/docs/reference/protocol-spec#integers): `0` if the element is not a member of the set, or when the key does not exist.
    ///     * [Integer](https:/redis.io/docs/reference/protocol-spec#integers): `1` if the element is a member of the set.
    @inlinable
    public static func sismember(key: RedisKey, member: String) -> RESPCommand {
        RESPCommand("SISMEMBER", key, member)
    }

    /// Returns all members of a set.
    ///
    /// - Documentation: [SMEMBERS](https:/redis.io/docs/latest/commands/smembers)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the set cardinality.
    /// - Categories: @read, @set, @slow
    /// - Response: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): all members of the set.
    @inlinable
    public static func smembers(key: RedisKey) -> RESPCommand {
        RESPCommand("SMEMBERS", key)
    }

    /// Determines whether multiple members belong to a set.
    ///
    /// - Documentation: [SMISMEMBER](https:/redis.io/docs/latest/commands/smismember)
    /// - Version: 6.2.0
    /// - Complexity: O(N) where N is the number of elements being checked for membership
    /// - Categories: @read, @set, @fast
    /// - Response: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list representing the membership of the given elements, in the same order as they are requested.
    @inlinable
    public static func smismember(key: RedisKey, member: String) -> RESPCommand {
        RESPCommand("SMISMEMBER", key, member)
    }

    /// Determines whether multiple members belong to a set.
    ///
    /// - Documentation: [SMISMEMBER](https:/redis.io/docs/latest/commands/smismember)
    /// - Version: 6.2.0
    /// - Complexity: O(N) where N is the number of elements being checked for membership
    /// - Categories: @read, @set, @fast
    /// - Response: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list representing the membership of the given elements, in the same order as they are requested.
    @inlinable
    public static func smismember(key: RedisKey, members: [String]) -> RESPCommand {
        RESPCommand("SMISMEMBER", key, members)
    }

    /// Moves a member from one set to another.
    ///
    /// - Documentation: [SMOVE](https:/redis.io/docs/latest/commands/smove)
    /// - Version: 1.0.0
    /// - Complexity: O(1)
    /// - Categories: @write, @set, @fast
    /// - Response: One of the following:
    ///     * [Integer](https:/redis.io/docs/reference/protocol-spec#integers): `1` if the element is moved.
    ///     * [Integer](https:/redis.io/docs/reference/protocol-spec#integers): `0` if the element is not a member of _source_ and no operation was performed.
    @inlinable
    public static func smove(source: RedisKey, destination: RedisKey, member: String) -> RESPCommand {
        RESPCommand("SMOVE", source, destination, member)
    }

    /// Returns one or more random members from a set after removing them. Deletes the set if the last member was popped.
    ///
    /// - Documentation: [SPOP](https:/redis.io/docs/latest/commands/spop)
    /// - Version: 1.0.0
    /// - Complexity: Without the count argument O(1), otherwise O(N) where N is the value of the passed count.
    /// - Categories: @write, @set, @fast
    /// - Response: One of the following:
    ///     * [Null](https:/redis.io/docs/reference/protocol-spec#nulls): if the key does not exist.
    ///     * [Bulk string](https:/redis.io/docs/reference/protocol-spec#bulk-strings): when called without the _count_ argument, the removed member.
    ///     * [Array](https:/redis.io/docs/reference/protocol-spec#arrays): when called with the _count_ argument, a list of the removed members.
    @inlinable
    public static func spop(key: RedisKey, count: Int? = nil) -> RESPCommand {
        RESPCommand("SPOP", key, count)
    }

    /// Get one or multiple random members from a set
    ///
    /// - Documentation: [SRANDMEMBER](https:/redis.io/docs/latest/commands/srandmember)
    /// - Version: 1.0.0
    /// - Complexity: Without the count argument O(1), otherwise O(N) where N is the absolute value of the passed count.
    /// - Categories: @read, @set, @slow
    /// - Response: One of the following:
    ///     * [Bulk string](https:/redis.io/docs/reference/protocol-spec#bulk-strings): without the additional _count_ argument, the command returns a randomly selected member, or a [Null](https:/redis.io/docs/reference/protocol-spec#nulls) when _key_ doesn't exist.
    ///     * [Array](https:/redis.io/docs/reference/protocol-spec#arrays): when the optional _count_ argument is passed, the command returns an array of members, or an empty array when _key_ doesn't exist.
    @inlinable
    public static func srandmember(key: RedisKey, count: Int? = nil) -> RESPCommand {
        RESPCommand("SRANDMEMBER", key, count)
    }

    /// Removes one or more members from a set. Deletes the set if the last member was removed.
    ///
    /// - Documentation: [SREM](https:/redis.io/docs/latest/commands/srem)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the number of members to be removed.
    /// - Categories: @write, @set, @fast
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): Number of members that were removed from the set, not including non existing members.
    @inlinable
    public static func srem(key: RedisKey, member: String) -> RESPCommand {
        RESPCommand("SREM", key, member)
    }

    /// Removes one or more members from a set. Deletes the set if the last member was removed.
    ///
    /// - Documentation: [SREM](https:/redis.io/docs/latest/commands/srem)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the number of members to be removed.
    /// - Categories: @write, @set, @fast
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): Number of members that were removed from the set, not including non existing members.
    @inlinable
    public static func srem(key: RedisKey, members: [String]) -> RESPCommand {
        RESPCommand("SREM", key, members)
    }

    /// Iterates over members of a set.
    ///
    /// - Documentation: [SSCAN](https:/redis.io/docs/latest/commands/sscan)
    /// - Version: 2.8.0
    /// - Complexity: O(1) for every call. O(N) for a complete iteration, including enough command calls for the cursor to return back to 0. N is the number of elements inside the collection.
    /// - Categories: @read, @set, @slow
    /// - Response: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): specifically, an array with two elements:
    ///     * The first element is a [Bulk string](https:/redis.io/docs/reference/protocol-spec#bulk-strings) that represents an unsigned 64-bit number, the cursor.
    ///     * The second element is an [Array](https:/redis.io/docs/reference/protocol-spec#arrays) with the names of scanned members.
    @inlinable
    public static func sscan(key: RedisKey, cursor: Int, pattern: String? = nil, count: Int? = nil) -> RESPCommand {
        RESPCommand("SSCAN", key, cursor, RESPWithToken("MATCH", pattern), RESPWithToken("COUNT", count))
    }

    /// Returns the union of multiple sets.
    ///
    /// - Documentation: [SUNION](https:/redis.io/docs/latest/commands/sunion)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @read, @set, @slow
    /// - Response: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public static func sunion(key: RedisKey) -> RESPCommand {
        RESPCommand("SUNION", key)
    }

    /// Returns the union of multiple sets.
    ///
    /// - Documentation: [SUNION](https:/redis.io/docs/latest/commands/sunion)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @read, @set, @slow
    /// - Response: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public static func sunion(keys: [RedisKey]) -> RESPCommand {
        RESPCommand("SUNION", keys)
    }

    /// Stores the union of multiple sets in a key.
    ///
    /// - Documentation: [SUNIONSTORE](https:/redis.io/docs/latest/commands/sunionstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @write, @set, @slow
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): Number of the elements in the resulting set.
    @inlinable
    public static func sunionstore(destination: RedisKey, key: RedisKey) -> RESPCommand {
        RESPCommand("SUNIONSTORE", destination, key)
    }

    /// Stores the union of multiple sets in a key.
    ///
    /// - Documentation: [SUNIONSTORE](https:/redis.io/docs/latest/commands/sunionstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @write, @set, @slow
    /// - Response: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): Number of the elements in the resulting set.
    @inlinable
    public static func sunionstore(destination: RedisKey, keys: [RedisKey]) -> RESPCommand {
        RESPCommand("SUNIONSTORE", destination, keys)
    }

}

extension RedisConnection {
    /// Adds one or more members to a set. Creates the key if it doesn't exist.
    ///
    /// - Documentation: [SADD](https:/redis.io/docs/latest/commands/sadd)
    /// - Version: 1.0.0
    /// - Complexity: O(1) for each element added, so O(N) to add N elements when the command is called with multiple arguments.
    /// - Categories: @write, @set, @fast
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of elements that were added to the set, not including all the elements already present in the set.
    @inlinable
    public func sadd(key: RedisKey, member: String) async throws -> Int {
        try await send("SADD", key, member).converting()
    }

    /// Adds one or more members to a set. Creates the key if it doesn't exist.
    ///
    /// - Documentation: [SADD](https:/redis.io/docs/latest/commands/sadd)
    /// - Version: 1.0.0
    /// - Complexity: O(1) for each element added, so O(N) to add N elements when the command is called with multiple arguments.
    /// - Categories: @write, @set, @fast
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of elements that were added to the set, not including all the elements already present in the set.
    @inlinable
    public func sadd(key: RedisKey, members: [String]) async throws -> Int {
        try await send("SADD", key, members).converting()
    }

    /// Returns the number of members in a set.
    ///
    /// - Documentation: [SCARD](https:/redis.io/docs/latest/commands/scard)
    /// - Version: 1.0.0
    /// - Complexity: O(1)
    /// - Categories: @read, @set, @fast
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): The cardinality (number of elements) of the set, or 0 if the key does not exist.
    @inlinable
    public func scard(key: RedisKey) async throws -> Int {
        try await send("SCARD", key).converting()
    }

    /// Returns the difference of multiple sets.
    ///
    /// - Documentation: [SDIFF](https:/redis.io/docs/latest/commands/sdiff)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @read, @set, @slow
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public func sdiff(key: RedisKey) async throws -> [RESPToken] {
        try await send("SDIFF", key).converting()
    }

    /// Returns the difference of multiple sets.
    ///
    /// - Documentation: [SDIFF](https:/redis.io/docs/latest/commands/sdiff)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @read, @set, @slow
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public func sdiff(keys: [RedisKey]) async throws -> [RESPToken] {
        try await send("SDIFF", keys).converting()
    }

    /// Stores the difference of multiple sets in a key.
    ///
    /// - Documentation: [SDIFFSTORE](https:/redis.io/docs/latest/commands/sdiffstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @write, @set, @slow
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of elements in the resulting set.
    @inlinable
    public func sdiffstore(destination: RedisKey, key: RedisKey) async throws -> Int {
        try await send("SDIFFSTORE", destination, key).converting()
    }

    /// Stores the difference of multiple sets in a key.
    ///
    /// - Documentation: [SDIFFSTORE](https:/redis.io/docs/latest/commands/sdiffstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @write, @set, @slow
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of elements in the resulting set.
    @inlinable
    public func sdiffstore(destination: RedisKey, keys: [RedisKey]) async throws -> Int {
        try await send("SDIFFSTORE", destination, keys).converting()
    }

    /// Returns the intersect of multiple sets.
    ///
    /// - Documentation: [SINTER](https:/redis.io/docs/latest/commands/sinter)
    /// - Version: 1.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @read, @set, @slow
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public func sinter(key: RedisKey) async throws -> [RESPToken] {
        try await send("SINTER", key).converting()
    }

    /// Returns the intersect of multiple sets.
    ///
    /// - Documentation: [SINTER](https:/redis.io/docs/latest/commands/sinter)
    /// - Version: 1.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @read, @set, @slow
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public func sinter(keys: [RedisKey]) async throws -> [RESPToken] {
        try await send("SINTER", keys).converting()
    }

    /// Returns the number of members of the intersect of multiple sets.
    ///
    /// - Documentation: [SINTERCARD](https:/redis.io/docs/latest/commands/sintercard)
    /// - Version: 7.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @read, @set, @slow
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of the elements in the resulting intersection.
    @inlinable
    public func sintercard(key: RedisKey, limit: Int? = nil) async throws -> Int {
        try await send("SINTERCARD", 1, key, RESPWithToken("LIMIT", limit)).converting()
    }

    /// Returns the number of members of the intersect of multiple sets.
    ///
    /// - Documentation: [SINTERCARD](https:/redis.io/docs/latest/commands/sintercard)
    /// - Version: 7.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @read, @set, @slow
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of the elements in the resulting intersection.
    @inlinable
    public func sintercard(keys: [RedisKey], limit: Int? = nil) async throws -> Int {
        try await send("SINTERCARD", RESPArrayWithCount(keys), RESPWithToken("LIMIT", limit)).converting()
    }

    /// Stores the intersect of multiple sets in a key.
    ///
    /// - Documentation: [SINTERSTORE](https:/redis.io/docs/latest/commands/sinterstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @write, @set, @slow
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of the elements in the result set.
    @inlinable
    public func sinterstore(destination: RedisKey, key: RedisKey) async throws -> Int {
        try await send("SINTERSTORE", destination, key).converting()
    }

    /// Stores the intersect of multiple sets in a key.
    ///
    /// - Documentation: [SINTERSTORE](https:/redis.io/docs/latest/commands/sinterstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
    /// - Categories: @write, @set, @slow
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): the number of the elements in the result set.
    @inlinable
    public func sinterstore(destination: RedisKey, keys: [RedisKey]) async throws -> Int {
        try await send("SINTERSTORE", destination, keys).converting()
    }

    /// Determines whether a member belongs to a set.
    ///
    /// - Documentation: [SISMEMBER](https:/redis.io/docs/latest/commands/sismember)
    /// - Version: 1.0.0
    /// - Complexity: O(1)
    /// - Categories: @read, @set, @fast
    /// - Returns: One of the following:
    ///     * [Integer](https:/redis.io/docs/reference/protocol-spec#integers): `0` if the element is not a member of the set, or when the key does not exist.
    ///     * [Integer](https:/redis.io/docs/reference/protocol-spec#integers): `1` if the element is a member of the set.
    @inlinable
    public func sismember(key: RedisKey, member: String) async throws -> Int {
        try await send("SISMEMBER", key, member).converting()
    }

    /// Returns all members of a set.
    ///
    /// - Documentation: [SMEMBERS](https:/redis.io/docs/latest/commands/smembers)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the set cardinality.
    /// - Categories: @read, @set, @slow
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): all members of the set.
    @inlinable
    public func smembers(key: RedisKey) async throws -> [RESPToken] {
        try await send("SMEMBERS", key).converting()
    }

    /// Determines whether multiple members belong to a set.
    ///
    /// - Documentation: [SMISMEMBER](https:/redis.io/docs/latest/commands/smismember)
    /// - Version: 6.2.0
    /// - Complexity: O(N) where N is the number of elements being checked for membership
    /// - Categories: @read, @set, @fast
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list representing the membership of the given elements, in the same order as they are requested.
    @inlinable
    public func smismember(key: RedisKey, member: String) async throws -> [RESPToken] {
        try await send("SMISMEMBER", key, member).converting()
    }

    /// Determines whether multiple members belong to a set.
    ///
    /// - Documentation: [SMISMEMBER](https:/redis.io/docs/latest/commands/smismember)
    /// - Version: 6.2.0
    /// - Complexity: O(N) where N is the number of elements being checked for membership
    /// - Categories: @read, @set, @fast
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list representing the membership of the given elements, in the same order as they are requested.
    @inlinable
    public func smismember(key: RedisKey, members: [String]) async throws -> [RESPToken] {
        try await send("SMISMEMBER", key, members).converting()
    }

    /// Moves a member from one set to another.
    ///
    /// - Documentation: [SMOVE](https:/redis.io/docs/latest/commands/smove)
    /// - Version: 1.0.0
    /// - Complexity: O(1)
    /// - Categories: @write, @set, @fast
    /// - Returns: One of the following:
    ///     * [Integer](https:/redis.io/docs/reference/protocol-spec#integers): `1` if the element is moved.
    ///     * [Integer](https:/redis.io/docs/reference/protocol-spec#integers): `0` if the element is not a member of _source_ and no operation was performed.
    @inlinable
    public func smove(source: RedisKey, destination: RedisKey, member: String) async throws -> Int {
        try await send("SMOVE", source, destination, member).converting()
    }

    /// Returns one or more random members from a set after removing them. Deletes the set if the last member was popped.
    ///
    /// - Documentation: [SPOP](https:/redis.io/docs/latest/commands/spop)
    /// - Version: 1.0.0
    /// - Complexity: Without the count argument O(1), otherwise O(N) where N is the value of the passed count.
    /// - Categories: @write, @set, @fast
    /// - Returns: One of the following:
    ///     * [Null](https:/redis.io/docs/reference/protocol-spec#nulls): if the key does not exist.
    ///     * [Bulk string](https:/redis.io/docs/reference/protocol-spec#bulk-strings): when called without the _count_ argument, the removed member.
    ///     * [Array](https:/redis.io/docs/reference/protocol-spec#arrays): when called with the _count_ argument, a list of the removed members.
    @inlinable
    public func spop(key: RedisKey, count: Int? = nil) async throws -> RESPToken {
        try await send("SPOP", key, count)
    }

    /// Get one or multiple random members from a set
    ///
    /// - Documentation: [SRANDMEMBER](https:/redis.io/docs/latest/commands/srandmember)
    /// - Version: 1.0.0
    /// - Complexity: Without the count argument O(1), otherwise O(N) where N is the absolute value of the passed count.
    /// - Categories: @read, @set, @slow
    /// - Returns: One of the following:
    ///     * [Bulk string](https:/redis.io/docs/reference/protocol-spec#bulk-strings): without the additional _count_ argument, the command returns a randomly selected member, or a [Null](https:/redis.io/docs/reference/protocol-spec#nulls) when _key_ doesn't exist.
    ///     * [Array](https:/redis.io/docs/reference/protocol-spec#arrays): when the optional _count_ argument is passed, the command returns an array of members, or an empty array when _key_ doesn't exist.
    @inlinable
    public func srandmember(key: RedisKey, count: Int? = nil) async throws -> RESPToken {
        try await send("SRANDMEMBER", key, count)
    }

    /// Removes one or more members from a set. Deletes the set if the last member was removed.
    ///
    /// - Documentation: [SREM](https:/redis.io/docs/latest/commands/srem)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the number of members to be removed.
    /// - Categories: @write, @set, @fast
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): Number of members that were removed from the set, not including non existing members.
    @inlinable
    public func srem(key: RedisKey, member: String) async throws -> Int {
        try await send("SREM", key, member).converting()
    }

    /// Removes one or more members from a set. Deletes the set if the last member was removed.
    ///
    /// - Documentation: [SREM](https:/redis.io/docs/latest/commands/srem)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the number of members to be removed.
    /// - Categories: @write, @set, @fast
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): Number of members that were removed from the set, not including non existing members.
    @inlinable
    public func srem(key: RedisKey, members: [String]) async throws -> Int {
        try await send("SREM", key, members).converting()
    }

    /// Iterates over members of a set.
    ///
    /// - Documentation: [SSCAN](https:/redis.io/docs/latest/commands/sscan)
    /// - Version: 2.8.0
    /// - Complexity: O(1) for every call. O(N) for a complete iteration, including enough command calls for the cursor to return back to 0. N is the number of elements inside the collection.
    /// - Categories: @read, @set, @slow
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): specifically, an array with two elements:
    ///     * The first element is a [Bulk string](https:/redis.io/docs/reference/protocol-spec#bulk-strings) that represents an unsigned 64-bit number, the cursor.
    ///     * The second element is an [Array](https:/redis.io/docs/reference/protocol-spec#arrays) with the names of scanned members.
    @inlinable
    public func sscan(key: RedisKey, cursor: Int, pattern: String? = nil, count: Int? = nil) async throws -> [RESPToken] {
        try await send("SSCAN", key, cursor, RESPWithToken("MATCH", pattern), RESPWithToken("COUNT", count)).converting()
    }

    /// Returns the union of multiple sets.
    ///
    /// - Documentation: [SUNION](https:/redis.io/docs/latest/commands/sunion)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @read, @set, @slow
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public func sunion(key: RedisKey) async throws -> [RESPToken] {
        try await send("SUNION", key).converting()
    }

    /// Returns the union of multiple sets.
    ///
    /// - Documentation: [SUNION](https:/redis.io/docs/latest/commands/sunion)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @read, @set, @slow
    /// - Returns: [Array](https:/redis.io/docs/reference/protocol-spec#arrays): a list with the members of the resulting set.
    @inlinable
    public func sunion(keys: [RedisKey]) async throws -> [RESPToken] {
        try await send("SUNION", keys).converting()
    }

    /// Stores the union of multiple sets in a key.
    ///
    /// - Documentation: [SUNIONSTORE](https:/redis.io/docs/latest/commands/sunionstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @write, @set, @slow
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): Number of the elements in the resulting set.
    @inlinable
    public func sunionstore(destination: RedisKey, key: RedisKey) async throws -> Int {
        try await send("SUNIONSTORE", destination, key).converting()
    }

    /// Stores the union of multiple sets in a key.
    ///
    /// - Documentation: [SUNIONSTORE](https:/redis.io/docs/latest/commands/sunionstore)
    /// - Version: 1.0.0
    /// - Complexity: O(N) where N is the total number of elements in all given sets.
    /// - Categories: @write, @set, @slow
    /// - Returns: [Integer](https:/redis.io/docs/reference/protocol-spec#integers): Number of the elements in the resulting set.
    @inlinable
    public func sunionstore(destination: RedisKey, keys: [RedisKey]) async throws -> Int {
        try await send("SUNIONSTORE", destination, keys).converting()
    }

}
