services:
  valkey:
    image: valkey/valkey:8.0
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "valkey-cli", "--raw", "incr", "ping"]
    volumes:
      - valkey_data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318 # OTLP/HTTP receiver
      - 16686:16686 # Jaeger Web UI

volumes:
  valkey_data:
